// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type BaseResponse struct {
	StatusCode int32  `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
}

type BindMfaqrcodeRequest struct {
	Mfa_secret string `form:"mfa_secret"`
	Mfa_code   string `form:"mfa_code"`
}

type BindMfaqrcodeResponse struct {
	Base BaseResponse `json:"base"`
}

type CommentBaseinfo struct {
	CommentID       string `json:"comment_id" gorm:"primaryKey;type:varchar(64)"`
	UserID          string `json:"user_id" gorm:"not null;type:varchar(64)"`
	VideoID         string `json:"video_id" gorm:"not null;type:varchar(64)"`
	Content         string `json:"content" gorm:"not null;type:varchar(1024)"` // 增加评论内容长度
	CreatedAt       string `json:"created_at" gorm:"autoCreateTime"`
	UpdatedAt       string `json:"updated_at" gorm:"autoUpdateTime"`
	DeletedAt       string `json:"deleted_at"`
	LikeCount       int32  `json:"like_count" gorm:"default:0;type:int"`
	ParentCommentID string `json:"parent_comment_id" gorm:"type:char(64);default:''"` // 父评论 ID，空字符串表示没有父评论
}

type CommentLiker struct {
	UserID    string `json:"user_id" gorm:"primaryKey;type:varchar(64)"`
	CommentID string `json:"comment_id" gorm:"primaryKey;type:varchar(64)"`
}

type CommentPareantCommentRequest struct {
	ParentCommentID string `form:"parent_comment_id"`
	CommentText     string `form:"comment_text"`
}

type CommentPareantCommentResponse struct {
	Base      BaseResponse `json:"base_response"`
	CommentID string       `json:"comment_id"`
}

type CommentVideoRequest struct {
	VideoID     string `form:"video_id"`
	CommentText string `form:"comment_text"`
}

type CommentVideoResponse struct {
	Base      BaseResponse `json:"base_response"`
	CommentID string       `json:"comment_id"`
}

type CreateChatRoomRequest struct {
	RoomName string   `form:"room_name"`
	Types    int32    `form:"types"` // 0: 私聊, 1: 群聊
	UserIDs  []string `form:"user_ids"`
}

type CreateChatRoomResponse struct {
	Base   BaseResponse `json:"base_response"`
	RoomID string       `json:"room_id"`
}

type DeleteCommentRequest struct {
	CommentID string `form:"comment_id"`
}

type DeleteCommentResponse struct {
	Base BaseResponse `json:"base_response"`
}

type GetChatRoomsRequest struct {
}

type GetChatRoomsResponse struct {
	Base    BaseResponse `json:"base_response"`
	RoomsId []string     `json:"chat_rooms"`
}

type GetCommentListRequest struct {
	VideoID    string `form:"video_id"`
	PageNumber int32  `form:"page_number"`
	PageSize   int32  `form:"page_size"`
}

type GetCommentListResponse struct {
	Base         BaseResponse      `json:"base_response"`
	CommentList  []CommentBaseinfo `json:"comment_list"`
	CommentCount int32             `json:"comment_count"`
}

type GetFansListRequest struct {
	PageNumber int32 `form:"page_number"`
	PageSize   int32 `form:"page_size"`
}

type GetFansListResponse struct {
	BaseResponse BaseResponse   `json:"base_response"`
	FansList     []UserBaseinfo `json:"fans_list"`
	FansCount    int32          `json:"fans_count"`
}

type GetFriendListRequest struct {
	PageNumber int32 `form:"page_number"`
	PageSize   int32 `form:"page_size"`
}

type GetFriendListResponse struct {
	BaseResponse BaseResponse   `json:"base_response"`
	FriendList   []UserBaseinfo `json:"friend_list"`
	FriendCount  int32          `json:"friend_count"`
}

type GetLikeListRequest struct {
	PageNumber int32 `form:"page_number"`
	PageSize   int32 `form:"page_size"`
}

type GetLikeListResponse struct {
	Base      BaseResponse    `json:"base_response"`
	VideoList []VideoBaseinfo `json:"video_list"`
	LikeCount int32           `json:"like_count"`
}

type GetMessagesRequest struct {
	RoomID     string `form:"room_id"`
	PageNumber int32  `form:"page_number"`
	PageSize   int32  `form:"page_size"`
}

type GetMessagesResponse struct {
	Base     BaseResponse  `json:"base_response"`
	Messages []MessageChat `json:"messages"`
}

type GetSubscriberListRequest struct {
	PageNumber int32 `form:"page_number"`
	PageSize   int32 `form:"page_size"`
}

type GetSubscriberListResponse struct {
	BaseResponse    BaseResponse   `json:"base_response"`
	SubscriberList  []UserBaseinfo `json:"subscriber_list"`
	SubscriberCount int32          `json:"subscriber_count"`
}

type GetVideoListRequest struct {
	UserID   string `form:"user_id"`
	PageSize int32  `form:"page_size"`
	PageNum  int32  `form:"page_num"`
}

type GetVideoListResponse struct {
	Base   BaseResponse    `json:"base"`
	Videos []VideoBaseinfo `json:"videos"`
}

type Item struct {
	Videos        VideoBaseinfo `json:"videos"`
	VideosPopular VideoPopular  `json:"videos_popular"`
}

type JoinChatRoomRequest struct {
	RoomID string `form:"room_id"`
}

type JoinChatRoomResponse struct {
	Base BaseResponse `json:"base_response"`
}

type LikeCommentRequest struct {
	CommentID string `form:"comment_id"`
	Liketype  int32  `form:"like_type"`
}

type LikeCommentResponse struct {
	Base BaseResponse `json:"base_response"`
}

type LikeVideoRequest struct {
	VideoID    string `form:"video_id"`
	ActionType int32  `form:"action_type"`
}

type LikeVideoResponse struct {
	Base BaseResponse `json:"base_response"`
}

type LoginRequest struct {
	Username string `form:"username"`
	Password string `form:"password"`
	MfaCode  string `form:"mfa_code"`
}

type LoginResponse struct {
	Base         BaseResponse `json:"base"`
	UserID       string       `json:"user_id"`
	AccessToken  string       `json:"access_token"`
	RefreshToken string       `json:"refresh_token" cookie:"refresh_token"`
}

type MessageChat struct {
	ID        string `json:"id" gorm:"primaryKey;type:varchar(64)"`
	RoomID    string `json:"room_id" gorm:"not null;type:varchar(64)"`
	SenderID  string `json:"sender_id" gorm:"not null;type:varchar(64)"`
	Content   string `json:"content" gorm:"not null;type:varchar(1024)"`
	CreatedAt string `json:"created_at" `
}

type MfaqrcodeRequest struct {
	Mfa_ticket string `form:"mfa_ticket"`
}

type MfaqrcodeResponse struct {
	Base       BaseResponse `json:"base"`
	QRCodeURL  string       `json:"qr_code"`
	Mfa_secret string       `json:"mfa_secret"`
}

type PublishVideoRequest struct {
	Title       string `form:"title"`
	Description string `form:"description"`
}

type PublishVideoResponse struct {
	Base    BaseResponse `json:"base"`
	VideoID string       `json:"video_id"`
}

type RefreshTokenRequest struct {
	RefreshToken string `cookie:"refresh_token"`
}

type RefreshTokenResponse struct {
	Base         BaseResponse `json:"base"`
	AccessToken  string       `json:"access_token"`
	RefreshToken string       `json:"refresh_token" cookie:"refresh_token"`
}

type RegisterRequest struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type RegisterResponse struct {
	Base   BaseResponse `json:"base"`
	UserID string       `json:"user_id"`
}

type SubscribeRequest struct {
	ToUserID   string `form:"to_user_id"`
	ActionType int32  `form:"action_type"`
}

type SubscribeResponse struct {
	BaseResponse BaseResponse `json:"base_response"`
}

type UserBaseinfo struct {
	UserID    string `json:"user_id" gorm:"primaryKey;type:varchar(64)"`  // 增加长度以兼容各种 ID 生成策略
	Username  string `json:"username" gorm:"unique;type:varchar(64)"`     // 增加长度
	Password  string `json:"password" gorm:"not null;type:varchar(255)"`  // 密码哈希通常较长，建议 255
	PhotoURL  string `json:"photo_url" gorm:"not null;type:varchar(255)"` // 修正：去掉了多余的引号，增加 URL 长度
	CreatedAt string `json:"created_at" gorm:"autoCreateTime"`
	UpdatedAt string `json:"updated_at" gorm:"autoUpdateTime"`
	DeletedAt string `json:"deleted_at"`
}

type UserFollow struct {
	FollowerID string `json:"follower_id" gorm:"primaryKey;type:varchar(64)"` // 联合主键：关注者
	UserID     string `json:"user_id" gorm:"primaryKey;type:varchar(64)"`     // 联合主键：被关注者
	Status     int32  `json:"status" gorm:"default:0;type:int"`               // 修正：default 和 type 之间加分号或空格
}

type UserInfoRequest struct {
	UserID string `form:"user_id"`
}

type UserInfoResponse struct {
	Base BaseResponse `json:"base"`
	User UserBaseinfo `json:"user"`
}

type User_chat struct {
	UserID   string `json:"user_id" gorm:"type:varchar(64)"`
	RoomID   string `json:"room_id" gorm:"primaryKey;type:varchar(64)"`
	Leix     int32  `json:"leix" gorm:"default:0;type:int"` // 0: 私聊, 1: 群聊
	RoomName string `json:"room_name" gorm:"type:varchar(255)"`
}

type User_mfa struct {
	UserID             string `json:"user_id" gorm:"primaryKey;type:varchar(64)"`
	MFASecret          string `json:"mfa_secret" gorm:"not null;type:varchar(255)"`
	MFAEnabled         bool   `json:"mfa_enabled" gorm:"default:false;type:boolean"`
	PasswordHash       string `json:"password_hash" gorm:"not null;type:varchar(255)"`
	MFA_Pending_secret string `json:"mfa_pending_secret" gorm:"type:varchar(255)"`
}

type UserphotoRequest struct {
	PhotoURL string `form:"photo_url"`
}

type UserphotoResponse struct {
	StatusCode int32  `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
}

type VideoBaseinfo struct {
	VideoID     string `json:"video_id" gorm:"primaryKey;type:varchar(64)"`
	AuthorID    string `json:"author_id" gorm:"not null;type:varchar(64)"`
	VideoURL    string `json:"video_url" gorm:"not null;type:varchar(512)"` // 增加 URL 长度
	CoverURL    string `json:"cover_url" gorm:"type:varchar(512)"`          // 增加 URL 长度
	Title       string `json:"title" gorm:"not null;type:varchar(255)"`     // 标题通常需要更长
	Description string `json:"description" gorm:"type:varchar(512)"`        // 增加描述长度
	CreatedAt   string `json:"created_at" gorm:"autoCreateTime"`
	UpdatedAt   string `json:"updated_at" gorm:"autoUpdateTime"`
	DeletedAt   string `json:"deleted_at"`
}

type VideoLiker struct {
	UserID  string `json:"user_id" gorm:"primaryKey;type:varchar(64)"`
	VideoID string `json:"video_id" gorm:"primaryKey;type:varchar(64)"`
}

type VideoPopular struct {
	VideoID      string `json:"video_id" gorm:"primaryKey;type:varchar(64)"`
	VisitCount   int64  `json:"visit_count" gorm:"default:0;type:bigint"` // 建议用 bigint 防止溢出
	LikeCount    int64  `json:"like_count" gorm:"default:0;type:bigint"`
	CommentCount int64  `json:"comment_count" gorm:"default:0;type:bigint"`
}

type VideoPopularRequest struct {
	PageSize int32 `form:"page_size"`
	PageNum  int32 `form:"page_num"`
}

type VideoPopularResponse struct {
	Base   BaseResponse `json:"base"`
	Videos []Item       `json:items"`
}

type VideoSearchRequest struct {
	Keyword  string `form:"keyword"`
	PageSize int32  `form:"page_size"`
	PageNum  int32  `form:"page_num"`
}

type VideoSearchResponse struct {
	Base   BaseResponse    `json:"base"`
	Videos []VideoBaseinfo `json:"videos"`
}

type WsChatRequest struct {
}
