// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type BaseResponse struct {
	StatusCode int32  `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
}

type CommentBaseinfo struct {
	CommentID string `json:"comment_id" gorm:"primaryKey;type:varchar(64)"`
	UserID    string `json:"user_id" gorm:"not null;type:varchar(64)"`
	VideoID   string `json:"video_id" gorm:"not null;type:varchar(64)"`
	Content   string `json:"content" gorm:"not null;type:varchar(1024)"` // 增加评论内容长度
	CreatedAt string `json:"created_at" gorm:"autoCreateTime"`
	UpdatedAt string `json:"updated_at" gorm:"autoUpdateTime"`
	DeletedAt string `json:"deleted_at"`
	LikeCount int32  `json:"like_count" gorm:"default:0;type:int"`
}

type CommentVideoRequest struct {
	VideoID     string `form:"video_id"`
	CommentText string `form:"comment_text"`
}

type CommentVideoResponse struct {
	Base      BaseResponse `json:"base_response"`
	CommentID string       `json:"comment_id"`
}

type DeleteCommentRequest struct {
	CommentID string `form:"comment_id"`
}

type DeleteCommentResponse struct {
	Base BaseResponse `json:"base_response"`
}

type GetCommentListRequest struct {
	VideoID    string `form:"video_id"`
	PageNumber int32  `form:"page_number"`
	PageSize   int32  `form:"page_size"`
}

type GetCommentListResponse struct {
	Base         BaseResponse      `json:"base_response"`
	CommentList  []CommentBaseinfo `json:"comment_list"`
	CommentCount int32             `json:"comment_count"`
}

type GetFansListRequest struct {
	PageNumber int32 `form:"page_number"`
	PageSize   int32 `form:"page_size"`
}

type GetFansListResponse struct {
	BaseResponse BaseResponse   `json:"base_response"`
	FansList     []UserBaseinfo `json:"fans_list"`
	FansCount    int32          `json:"fans_count"`
}

type GetFriendListRequest struct {
	PageNumber int32 `form:"page_number"`
	PageSize   int32 `form:"page_size"`
}

type GetFriendListResponse struct {
	BaseResponse BaseResponse   `json:"base_response"`
	FriendList   []UserBaseinfo `json:"friend_list"`
	FriendCount  int32          `json:"friend_count"`
}

type GetLikeListRequest struct {
	PageNumber int32 `form:"page_number"`
	PageSize   int32 `form:"page_size"`
}

type GetLikeListResponse struct {
	Base      BaseResponse    `json:"base_response"`
	VideoList []VideoBaseinfo `json:"video_list"`
	LikeCount int32           `json:"like_count"`
}

type GetSubscriberListRequest struct {
	PageNumber int32 `form:"page_number"`
	PageSize   int32 `form:"page_size"`
}

type GetSubscriberListResponse struct {
	BaseResponse    BaseResponse   `json:"base_response"`
	SubscriberList  []UserBaseinfo `json:"subscriber_list"`
	SubscriberCount int32          `json:"subscriber_count"`
}

type GetVideoListRequest struct {
	PageSize int32 `form:"page_size"`
	PageNum  int32 `form:"page_num"`
}

type GetVideoListResponse struct {
	Base   BaseResponse    `json:"base"`
	Videos []VideoBaseinfo `json:"videos"`
}

type LikeVideoRequest struct {
	VideoID    string `form:"video_id"`
	ActionType int32  `form:"action_type"`
}

type LikeVideoResponse struct {
	Base BaseResponse `json:"base_response"`
}

type LoginRequest struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type LoginResponse struct {
	Base         BaseResponse `json:"base"`
	UserID       string       `json:"user_id"`
	AccessToken  string       `json:"access_token"`
	RefreshToken string       `json:"refresh_token" cookie:"refresh_token"`
}

type ParentComment struct {
	CommentID       string `json:"comment_id" gorm:"primaryKey;type:varchar(64)"`
	ParentCommentID string `json:"parent_comment_id" gorm:"type:varchar(64)"` // 修复字段名映射
}

type PublishVideoRequest struct {
	Title       string `form:"title"`
	Description string `form:"description"`
}

type PublishVideoResponse struct {
	Base    BaseResponse `json:"base"`
	VideoID string       `json:"video_id"`
}

type RefreshTokenRequest struct {
	RefreshToken string `cookie:"refresh_token"`
}

type RefreshTokenResponse struct {
	Base         BaseResponse `json:"base"`
	AccessToken  string       `json:"access_token"`
	RefreshToken string       `json:"refresh_token" cookie:"refresh_token"`
}

type RegisterRequest struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type RegisterResponse struct {
	Base   BaseResponse `json:"base"`
	UserID string       `json:"user_id"`
}

type SubscribeRequest struct {
	UserID     string `form:"user_id"`
	ToUserID   string `form:"to_user_id"`
	ActionType int32  `form:"action_type"`
}

type SubscribeResponse struct {
	BaseResponse BaseResponse `json:"base_response"`
}

type UserBaseinfo struct {
	UserID    string `json:"user_id" gorm:"primaryKey;type:varchar(64)"`                                       // 增加长度以兼容各种 ID 生成策略
	Username  string `json:"username" gorm:"unique;type:varchar(64)"`                                          // 增加长度
	Password  string `json:"password" gorm:"not null;type:varchar(255)"`                                       // 密码哈希通常较长，建议 255
	PhotoURL  string `json:"photo_url" gorm:"default:https://example.com/default_photo.jpg;type:varchar(512)"` // 修正：去掉了多余的引号，增加 URL 长度
	CreatedAt string `json:"created_at" gorm:"autoCreateTime"`
	UpdatedAt string `json:"updated_at" gorm:"autoUpdateTime"`
	DeletedAt string `json:"deleted_at"`
}

type UserFollow struct {
	FollowerID string `json:"follower_id" gorm:"primaryKey;type:varchar(64)"` // 联合主键：关注者
	UserID     string `json:"user_id" gorm:"primaryKey;type:varchar(64)"`     // 联合主键：被关注者
	Status     int32  `json:"status" gorm:"default:0;type:int"`               // 修正：default 和 type 之间加分号或空格
}

type UserInfoRequest struct {
	UserID string `form:"user_id"`
}

type UserInfoResponse struct {
	Base BaseResponse `json:"base"`
	User UserBaseinfo `json:"user"`
}

type UserphotoRequest struct {
	PhotoURL string `form:"photo_url"`
}

type UserphotoResponse struct {
	StatusCode int32  `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
}

type VideoBaseinfo struct {
	VideoID      string `json:"video_id" gorm:"primaryKey;type:varchar(64)"`
	AuthorID     string `json:"author_id" gorm:"not null;type:varchar(64)"`
	VideoURL     string `json:"video_url" gorm:"not null;type:varchar(512)"` // 增加 URL 长度
	CoverURL     string `json:"cover_url" gorm:"type:varchar(512)"`          // 增加 URL 长度
	Title        string `json:"title" gorm:"not null;type:varchar(255)"`     // 标题通常需要更长
	Description  string `json:"description" gorm:"type:varchar(512)"`        // 增加描述长度
	CreatedAt    string `json:"created_at" gorm:"autoCreateTime"`
	UpdatedAt    string `json:"updated_at" gorm:"autoUpdateTime"`
	DeletedAt    string `json:"deleted_at"`
	VisitCount   int64  `json:"visit_count" gorm:"default:0;type:bigint"` // 建议用 bigint 防止溢出
	LikeCount    int64  `json:"like_count" gorm:"default:0;type:bigint"`
	CommentCount int64  `json:"comment_count" gorm:"default:0;type:bigint"`
}

type VideoLiker struct {
	UserID  string `json:"user_id" gorm:"primaryKey;type:varchar(64)"`
	VideoID string `json:"video_id" gorm:"primaryKey;type:varchar(64)"`
}

type VideoPopular struct {
	VideoID      string `json:"video_id" gorm:"primaryKey;type:varchar(64)"`
	VisitCount   int64  `json:"visit_count" gorm:"default:0;type:bigint"` // 建议用 bigint 防止溢出
	LikeCount    int64  `json:"like_count" gorm:"default:0;type:bigint"`
	CommentCount int64  `json:"comment_count" gorm:"default:0;type:bigint"`
}

type VideoPopularRequest struct {
	PageSize int32 `form:"page_size"`
	PageNum  int32 `form:"page_num"`
}

type VideoPopularResponse struct {
	Base   BaseResponse    `json:"base"`
	Videos []VideoBaseinfo `json:"videos"`
}

type VideoSearchRequest struct {
	Keyword  string `form:"keyword"`
	PageSize int32  `form:"page_size"`
	PageNum  int32  `form:"page_num"`
}

type VideoSearchResponse struct {
	Base   BaseResponse    `json:"base"`
	Videos []VideoBaseinfo `json:"videos"`
}
