version: "2"

run:
  timeout: 5m
  skip-dirs:
    - .gocache

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - revive
    - gocritic
    - bodyclose
    - misspell
    - errorlint
    - gocognit
    - contextcheck
  disable:
    - wsl
    - nlreturn
  settings:
    revive:
      rules:
        - name: exported
          disabled: true
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gocognit
          - wrapcheck
      - path: _test\.go
        text: "SA1029:"
        linters:
          - staticcheck
