services:
  gateway:
    build:
      context: .
      dockerfile: app/gateway/api/Dockerfile
    ports:
      - "8888:8888"
    command: ./gateway -f etc/tiktok-api.yaml
    depends_on:
      etcd:
        condition: service_started
      user-rpc:
        condition: service_started
      video-rpc:
        condition: service_started
      interaction-rpc:
        condition: service_started
      communication-rpc:
        condition: service_started
      chat-rpc:
        condition: service_started
    restart: unless-stopped

  user-rpc:
    build:
      context: .
      dockerfile: app/user/rpc/Dockerfile
    ports:
      - "8890:8890"
    depends_on:
      etcd:
        condition: service_started
      mysql:
        condition: service_started
      redis:
        condition: service_started
    restart: unless-stopped

  video-rpc:
    build:
      context: .
      dockerfile: app/video/rpc/Dockerfile
    ports:
      - "8891:8891"
    environment:
      GOZERO_LOG_LEVEL: error
    depends_on:
      etcd:
        condition: service_started
      mysql:
        condition: service_started
    restart: unless-stopped

  interaction-rpc:
    build:
      context: .
      dockerfile: app/interaction/rpc/Dockerfile
    ports:
      - "8892:8892"
    depends_on:
      etcd:
        condition: service_started
      mysql:
        condition: service_started
    restart: unless-stopped

  communication-rpc:
    build:
      context: .
      dockerfile: app/communication/rpc/Dockerfile
    ports:
      - "8893:8893"
    depends_on:
      etcd:
        condition: service_started
      mysql:
        condition: service_started
    restart: unless-stopped

  chat-rpc:
    build:
      context: .
      dockerfile: app/chat/rpc/Dockerfile
    ports:
      - "8894:8894"
    depends_on:
      etcd:
        condition: service_started
      mysql:
        condition: service_started
      redis:
        condition: service_started
      kafka:
        condition: service_healthy
    restart: unless-stopped
