// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: communication.proto

package server

import (
	"context"

	"go_zero-tiktok/app/communication/rpc/communication_pb"
	"go_zero-tiktok/app/communication/rpc/internal/logic"
	"go_zero-tiktok/app/communication/rpc/internal/svc"
)

type CommunicationServiceServer struct {
	svcCtx *svc.ServiceContext
	communication_pb.UnimplementedCommunicationServiceServer
}

func NewCommunicationServiceServer(svcCtx *svc.ServiceContext) *CommunicationServiceServer {
	return &CommunicationServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *CommunicationServiceServer) Subscribe(ctx context.Context, in *communication_pb.SubscribeRequest) (*communication_pb.SubscribeResponse, error) {
	l := logic.NewSubscribeLogic(ctx, s.svcCtx)
	return l.Subscribe(in)
}

func (s *CommunicationServiceServer) GetFansList(ctx context.Context, in *communication_pb.GetFansListRequest) (*communication_pb.GetFansListResponse, error) {
	l := logic.NewGetFansListLogic(ctx, s.svcCtx)
	return l.GetFansList(in)
}

func (s *CommunicationServiceServer) GetSubscriberList(ctx context.Context, in *communication_pb.GetSubscriberListRequest) (*communication_pb.GetSubscriberListResponse, error) {
	l := logic.NewGetSubscriberListLogic(ctx, s.svcCtx)
	return l.GetSubscriberList(in)
}

func (s *CommunicationServiceServer) GetFriendList(ctx context.Context, in *communication_pb.GetFriendListRequest) (*communication_pb.GetFriendListResponse, error) {
	l := logic.NewGetFriendListLogic(ctx, s.svcCtx)
	return l.GetFriendList(in)
}
