// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	communication "go_zero-tiktok/internal/handler/communication"
	interaction "go_zero-tiktok/internal/handler/interaction"
	user "go_zero-tiktok/internal/handler/user"
	video "go_zero-tiktok/internal/handler/video"
	"go_zero-tiktok/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/follower/list",
				Handler: communication.GetFansListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/following/list",
				Handler: communication.GetSubscriberListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/friend/list",
				Handler: communication.GetFriendListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/relation/action",
				Handler: communication.SubscribeHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/comment/delete",
				Handler: interaction.DeleteCommentHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/comment/list",
				Handler: interaction.GetCommentListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/comment/publish",
				Handler: interaction.CommentVideoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/like/action",
				Handler: interaction.LikeVideoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/like/list",
				Handler: interaction.GetLikeListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/user/info",
				Handler: user.GetUserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: user.RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/token/refresh",
				Handler: user.RefreshTokenHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPut,
				Path:    "/user/avatar/upload",
				Handler: user.PostUserPhotoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/video/list",
				Handler: video.GetVideoListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/video/popular",
				Handler: video.VideoPopularHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/video/search",
				Handler: video.VideoSearchHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/video/publish",
				Handler: video.PublishVideoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
