// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: interaction.proto

package interactionservice

import (
	"context"

	"go_zero-tiktok/app/interaction/rpc/interaction_pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CommentInfo            = interaction_pb.CommentInfo
	CommentVideoRequest    = interaction_pb.CommentVideoRequest
	CommentVideoResponse   = interaction_pb.CommentVideoResponse
	DeleteCommentRequest   = interaction_pb.DeleteCommentRequest
	DeleteCommentResponse  = interaction_pb.DeleteCommentResponse
	GetCommentListRequest  = interaction_pb.GetCommentListRequest
	GetCommentListResponse = interaction_pb.GetCommentListResponse
	LikeCommentRequest     = interaction_pb.LikeCommentRequest
	LikeCommentResponse    = interaction_pb.LikeCommentResponse
	ReplyCommentRequest    = interaction_pb.ReplyCommentRequest
	ReplyCommentResponse   = interaction_pb.ReplyCommentResponse

	InteractionService interface {
		CommentVideo(ctx context.Context, in *CommentVideoRequest, opts ...grpc.CallOption) (*CommentVideoResponse, error)
		ReplyComment(ctx context.Context, in *ReplyCommentRequest, opts ...grpc.CallOption) (*ReplyCommentResponse, error)
		DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*DeleteCommentResponse, error)
		GetCommentList(ctx context.Context, in *GetCommentListRequest, opts ...grpc.CallOption) (*GetCommentListResponse, error)
		LikeComment(ctx context.Context, in *LikeCommentRequest, opts ...grpc.CallOption) (*LikeCommentResponse, error)
	}

	defaultInteractionService struct {
		cli zrpc.Client
	}
)

func NewInteractionService(cli zrpc.Client) InteractionService {
	return &defaultInteractionService{
		cli: cli,
	}
}

func (m *defaultInteractionService) CommentVideo(ctx context.Context, in *CommentVideoRequest, opts ...grpc.CallOption) (*CommentVideoResponse, error) {
	client := interaction_pb.NewInteractionServiceClient(m.cli.Conn())
	return client.CommentVideo(ctx, in, opts...)
}

func (m *defaultInteractionService) ReplyComment(ctx context.Context, in *ReplyCommentRequest, opts ...grpc.CallOption) (*ReplyCommentResponse, error) {
	client := interaction_pb.NewInteractionServiceClient(m.cli.Conn())
	return client.ReplyComment(ctx, in, opts...)
}

func (m *defaultInteractionService) DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*DeleteCommentResponse, error) {
	client := interaction_pb.NewInteractionServiceClient(m.cli.Conn())
	return client.DeleteComment(ctx, in, opts...)
}

func (m *defaultInteractionService) GetCommentList(ctx context.Context, in *GetCommentListRequest, opts ...grpc.CallOption) (*GetCommentListResponse, error) {
	client := interaction_pb.NewInteractionServiceClient(m.cli.Conn())
	return client.GetCommentList(ctx, in, opts...)
}

func (m *defaultInteractionService) LikeComment(ctx context.Context, in *LikeCommentRequest, opts ...grpc.CallOption) (*LikeCommentResponse, error) {
	client := interaction_pb.NewInteractionServiceClient(m.cli.Conn())
	return client.LikeComment(ctx, in, opts...)
}
