// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	communication "go_zero-tiktok/app/gateway/api/internal/handler/communication"
	interaction "go_zero-tiktok/app/gateway/api/internal/handler/interaction"
	user "go_zero-tiktok/app/gateway/api/internal/handler/user"
	video "go_zero-tiktok/app/gateway/api/internal/handler/video"
	"go_zero-tiktok/app/gateway/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RateLimit},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/users/me/followers",
					Handler: communication.GetFansListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/users/me/following",
					Handler: communication.GetSubscriberListHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/users/me/following/:id",
					Handler: communication.SubscribeHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/users/me/following/:id",
					Handler: communication.UnsubscribeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/users/me/friends",
					Handler: communication.GetFriendListHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RateLimit},
			[]rest.Route{
				{
					Method:  http.MethodDelete,
					Path:    "/comments/:id",
					Handler: interaction.DeleteCommentHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/comments/:id/like",
					Handler: interaction.LikeCommentHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/comments/:id/like",
					Handler: interaction.CancelLikeCommentHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/comments/:id/replies",
					Handler: interaction.ReplyCommentHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/users/me/likes",
					Handler: interaction.GetLikeListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/videos/:id/comments",
					Handler: interaction.CommentVideoHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/videos/:id/comments",
					Handler: interaction.GetCommentListHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/videos/:id/like",
					Handler: interaction.LikeVideoHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/videos/:id/like",
					Handler: interaction.CancelLikeVideoHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RateLimit},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/sessions",
					Handler: user.LoginHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/sessions/refresh",
					Handler: user.RefreshTokenHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/users",
					Handler: user.RegisterHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RateLimit},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/users/me",
					Handler: user.GetUserInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/users/me/mfa/bind",
					Handler: user.BindMfaHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/users/me/mfa/qr",
					Handler: user.GetMfaQRCodeHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/users/me/photo",
					Handler: user.UpdateUserPhotoHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RateLimit},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/feed-items",
					Handler: video.GetFeedVideoHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/users/:id/videos",
					Handler: video.GetVideoListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/videos/popular",
					Handler: video.VideoPopularHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/videos/search",
					Handler: video.VideoSearchHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RateLimit},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/videos",
					Handler: video.PublishVideoHandler(serverCtx),
				},
			}...,
		),
	)
}
