// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: communication.proto

package communicationservice

import (
	"context"

	"go_zero-tiktok/app/communication/rpc/communication_pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CountUnreadRequest        = communication_pb.CountUnreadRequest
	CountUnreadResponse       = communication_pb.CountUnreadResponse
	CreateMessageRequest      = communication_pb.CreateMessageRequest
	CreateMessageResponse     = communication_pb.CreateMessageResponse
	GetFansListRequest        = communication_pb.GetFansListRequest
	GetFansListResponse       = communication_pb.GetFansListResponse
	GetFriendListRequest      = communication_pb.GetFriendListRequest
	GetFriendListResponse     = communication_pb.GetFriendListResponse
	GetMessagesRequest        = communication_pb.GetMessagesRequest
	GetMessagesResponse       = communication_pb.GetMessagesResponse
	GetSubscriberListRequest  = communication_pb.GetSubscriberListRequest
	GetSubscriberListResponse = communication_pb.GetSubscriberListResponse
	MarkReadRequest           = communication_pb.MarkReadRequest
	MarkReadResponse          = communication_pb.MarkReadResponse
	MessageInfo               = communication_pb.MessageInfo
	SubscribeRequest          = communication_pb.SubscribeRequest
	SubscribeResponse         = communication_pb.SubscribeResponse

	CommunicationService interface {
		Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeResponse, error)
		GetFansList(ctx context.Context, in *GetFansListRequest, opts ...grpc.CallOption) (*GetFansListResponse, error)
		GetSubscriberList(ctx context.Context, in *GetSubscriberListRequest, opts ...grpc.CallOption) (*GetSubscriberListResponse, error)
		GetFriendList(ctx context.Context, in *GetFriendListRequest, opts ...grpc.CallOption) (*GetFriendListResponse, error)
		CreateMessage(ctx context.Context, in *CreateMessageRequest, opts ...grpc.CallOption) (*CreateMessageResponse, error)
		GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error)
		CountUnread(ctx context.Context, in *CountUnreadRequest, opts ...grpc.CallOption) (*CountUnreadResponse, error)
		MarkRead(ctx context.Context, in *MarkReadRequest, opts ...grpc.CallOption) (*MarkReadResponse, error)
	}

	defaultCommunicationService struct {
		cli zrpc.Client
	}
)

func NewCommunicationService(cli zrpc.Client) CommunicationService {
	return &defaultCommunicationService{
		cli: cli,
	}
}

func (m *defaultCommunicationService) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeResponse, error) {
	client := communication_pb.NewCommunicationServiceClient(m.cli.Conn())
	return client.Subscribe(ctx, in, opts...)
}

func (m *defaultCommunicationService) GetFansList(ctx context.Context, in *GetFansListRequest, opts ...grpc.CallOption) (*GetFansListResponse, error) {
	client := communication_pb.NewCommunicationServiceClient(m.cli.Conn())
	return client.GetFansList(ctx, in, opts...)
}

func (m *defaultCommunicationService) GetSubscriberList(ctx context.Context, in *GetSubscriberListRequest, opts ...grpc.CallOption) (*GetSubscriberListResponse, error) {
	client := communication_pb.NewCommunicationServiceClient(m.cli.Conn())
	return client.GetSubscriberList(ctx, in, opts...)
}

func (m *defaultCommunicationService) GetFriendList(ctx context.Context, in *GetFriendListRequest, opts ...grpc.CallOption) (*GetFriendListResponse, error) {
	client := communication_pb.NewCommunicationServiceClient(m.cli.Conn())
	return client.GetFriendList(ctx, in, opts...)
}

func (m *defaultCommunicationService) CreateMessage(ctx context.Context, in *CreateMessageRequest, opts ...grpc.CallOption) (*CreateMessageResponse, error) {
	client := communication_pb.NewCommunicationServiceClient(m.cli.Conn())
	return client.CreateMessage(ctx, in, opts...)
}

func (m *defaultCommunicationService) GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error) {
	client := communication_pb.NewCommunicationServiceClient(m.cli.Conn())
	return client.GetMessages(ctx, in, opts...)
}

func (m *defaultCommunicationService) CountUnread(ctx context.Context, in *CountUnreadRequest, opts ...grpc.CallOption) (*CountUnreadResponse, error) {
	client := communication_pb.NewCommunicationServiceClient(m.cli.Conn())
	return client.CountUnread(ctx, in, opts...)
}

func (m *defaultCommunicationService) MarkRead(ctx context.Context, in *MarkReadRequest, opts ...grpc.CallOption) (*MarkReadResponse, error) {
	client := communication_pb.NewCommunicationServiceClient(m.cli.Conn())
	return client.MarkRead(ctx, in, opts...)
}
