// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: communication.proto

package communicationservice

import (
	"context"

	"go_zero-tiktok/app/communication/rpc/communication_pb/communication_pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetFansListRequest        = communication_pb.GetFansListRequest
	GetFansListResponse       = communication_pb.GetFansListResponse
	GetFriendListRequest      = communication_pb.GetFriendListRequest
	GetFriendListResponse     = communication_pb.GetFriendListResponse
	GetSubscriberListRequest  = communication_pb.GetSubscriberListRequest
	GetSubscriberListResponse = communication_pb.GetSubscriberListResponse
	SubscribeRequest          = communication_pb.SubscribeRequest
	SubscribeResponse         = communication_pb.SubscribeResponse
	UserInfo                  = communication_pb.UserInfo

	CommunicationService interface {
		Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeResponse, error)
		GetFansList(ctx context.Context, in *GetFansListRequest, opts ...grpc.CallOption) (*GetFansListResponse, error)
		GetSubscriberList(ctx context.Context, in *GetSubscriberListRequest, opts ...grpc.CallOption) (*GetSubscriberListResponse, error)
		GetFriendList(ctx context.Context, in *GetFriendListRequest, opts ...grpc.CallOption) (*GetFriendListResponse, error)
	}

	defaultCommunicationService struct {
		cli zrpc.Client
	}
)

func NewCommunicationService(cli zrpc.Client) CommunicationService {
	return &defaultCommunicationService{
		cli: cli,
	}
}

func (m *defaultCommunicationService) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeResponse, error) {
	client := communication_pb.NewCommunicationServiceClient(m.cli.Conn())
	return client.Subscribe(ctx, in, opts...)
}

func (m *defaultCommunicationService) GetFansList(ctx context.Context, in *GetFansListRequest, opts ...grpc.CallOption) (*GetFansListResponse, error) {
	client := communication_pb.NewCommunicationServiceClient(m.cli.Conn())
	return client.GetFansList(ctx, in, opts...)
}

func (m *defaultCommunicationService) GetSubscriberList(ctx context.Context, in *GetSubscriberListRequest, opts ...grpc.CallOption) (*GetSubscriberListResponse, error) {
	client := communication_pb.NewCommunicationServiceClient(m.cli.Conn())
	return client.GetSubscriberList(ctx, in, opts...)
}

func (m *defaultCommunicationService) GetFriendList(ctx context.Context, in *GetFriendListRequest, opts ...grpc.CallOption) (*GetFriendListResponse, error) {
	client := communication_pb.NewCommunicationServiceClient(m.cli.Conn())
	return client.GetFriendList(ctx, in, opts...)
}
