// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: interaction.proto

package server

import (
	"context"

	"go_zero-tiktok/app/interaction/rpc/interaction_pb"
	"go_zero-tiktok/app/interaction/rpc/internal/logic"
	"go_zero-tiktok/app/interaction/rpc/internal/svc"
)

type InteractionServiceServer struct {
	svcCtx *svc.ServiceContext
	interaction_pb.UnimplementedInteractionServiceServer
}

func NewInteractionServiceServer(svcCtx *svc.ServiceContext) *InteractionServiceServer {
	return &InteractionServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *InteractionServiceServer) CommentVideo(ctx context.Context, in *interaction_pb.CommentVideoRequest) (*interaction_pb.CommentVideoResponse, error) {
	l := logic.NewCommentVideoLogic(ctx, s.svcCtx)
	return l.CommentVideo(in)
}

func (s *InteractionServiceServer) ReplyComment(ctx context.Context, in *interaction_pb.ReplyCommentRequest) (*interaction_pb.ReplyCommentResponse, error) {
	l := logic.NewReplyCommentLogic(ctx, s.svcCtx)
	return l.ReplyComment(in)
}

func (s *InteractionServiceServer) DeleteComment(ctx context.Context, in *interaction_pb.DeleteCommentRequest) (*interaction_pb.DeleteCommentResponse, error) {
	l := logic.NewDeleteCommentLogic(ctx, s.svcCtx)
	return l.DeleteComment(in)
}

func (s *InteractionServiceServer) GetCommentList(ctx context.Context, in *interaction_pb.GetCommentListRequest) (*interaction_pb.GetCommentListResponse, error) {
	l := logic.NewGetCommentListLogic(ctx, s.svcCtx)
	return l.GetCommentList(in)
}

func (s *InteractionServiceServer) LikeComment(ctx context.Context, in *interaction_pb.LikeCommentRequest) (*interaction_pb.LikeCommentResponse, error) {
	l := logic.NewLikeCommentLogic(ctx, s.svcCtx)
	return l.LikeComment(in)
}
