// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type BaseResponse struct {
	StatusCode int32  `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
}

type BindMfaRequest struct {
	MfaSecret string `form:"mfa_secret"`
	MfaCode   string `form:"mfa_code"`
}

type BindMfaResponse struct {
	Base BaseResponse `json:"base"`
}

type CancelFavoriteVideoRequest struct {
	VideoId int64 `path:"id"`
}

type CancelFavoriteVideoResponse struct {
	Base BaseResponse `json:"base"`
}

type CancelLikeCommentRequest struct {
	CommentId int64 `path:"id"`
}

type CancelLikeCommentResponse struct {
	Base BaseResponse `json:"base"`
}

type CancelLikeVideoRequest struct {
	VideoId int64 `path:"id"`
}

type CancelLikeVideoResponse struct {
	Base BaseResponse `json:"base"`
}

type CommentBaseinfo struct {
	CommentID       int64  `json:"comment_id,string"`
	UserID          int64  `json:"user_id,string"`
	VideoID         int64  `json:"video_id,string"`
	Content         string `json:"content"`
	CreatedAt       string `json:"created_at"`
	UpdatedAt       string `json:"updated_at"`
	DeletedAt       string `json:"deleted_at"`
	LikeCount       int32  `json:"like_count"`
	ParentCommentID int64  `json:"parent_comment_id,string"`
}

type CommentVideoRequest struct {
	VideoId     int64  `path:"id"`
	CommentText string `form:"comment_text"`
}

type CommentVideoResponse struct {
	Base      BaseResponse `json:"base"`
	CommentID int64        `json:"comment_id,string"`
}

type DeleteCommentRequest struct {
	CommentId int64 `path:"id"`
}

type DeleteCommentResponse struct {
	Base BaseResponse `json:"base"`
}

type FavoriteVideoRequest struct {
	VideoId int64 `path:"id"`
}

type FavoriteVideoResponse struct {
	Base BaseResponse `json:"base"`
}

type FeedVideoRequest struct {
	LastTime string `form:"last_time"`
	PageNum  int32  `form:"page_num"`
	PageSize int32  `form:"page_size"`
}

type FeedVideoResponse struct {
	Base  BaseResponse `json:"base"`
	Total int64        `json:"total"`
	Items []Item       `json:"items"`
}

type GetCommentListRequest struct {
	VideoId  int64 `path:"id"`
	PageNum  int32 `form:"page_num"`
	PageSize int32 `form:"page_size"`
}

type GetCommentListResponse struct {
	Base         BaseResponse      `json:"base"`
	CommentList  []CommentBaseinfo `json:"comment_list"`
	CommentCount int64             `json:"comment_count"`
}

type GetFansListRequest struct {
	PageNum  int32 `form:"page_num"`
	PageSize int32 `form:"page_size"`
}

type GetFansListResponse struct {
	Base      BaseResponse   `json:"base"`
	FansList  []UserBaseinfo `json:"fans_list"`
	FansCount int64          `json:"fans_count"`
}

type GetFavoriteListRequest struct {
	PageNum  int32 `form:"page_num"`
	PageSize int32 `form:"page_size"`
}

type GetFavoriteListResponse struct {
	Base          BaseResponse    `json:"base"`
	VideoList     []VideoBaseinfo `json:"video_list"`
	FavoriteCount int64           `json:"favorite_count"`
}

type GetFriendListRequest struct {
	PageNum  int32 `form:"page_num"`
	PageSize int32 `form:"page_size"`
}

type GetFriendListResponse struct {
	Base        BaseResponse   `json:"base"`
	FriendList  []UserBaseinfo `json:"friend_list"`
	FriendCount int64          `json:"friend_count"`
}

type GetLikeListRequest struct {
	PageNum  int32 `form:"page_num"`
	PageSize int32 `form:"page_size"`
}

type GetLikeListResponse struct {
	Base      BaseResponse    `json:"base"`
	VideoList []VideoBaseinfo `json:"video_list"`
	LikeCount int64           `json:"like_count"`
}

type GetMfaQRCodeRequest struct {
}

type GetMfaQRCodeResponse struct {
	Base      BaseResponse `json:"base"`
	QRCodeURL string       `json:"qr_code_url"`
	MfaSecret string       `json:"mfa_secret"`
}

type GetSubscriberListRequest struct {
	PageNum  int32 `form:"page_num"`
	PageSize int32 `form:"page_size"`
}

type GetSubscriberListResponse struct {
	Base            BaseResponse   `json:"base"`
	SubscriberList  []UserBaseinfo `json:"subscriber_list"`
	SubscriberCount int64          `json:"subscriber_count"`
}

type GetUserInfoRequest struct {
}

type GetUserInfoResponse struct {
	Base BaseResponse `json:"base"`
	User UserBaseinfo `json:"user"`
}

type GetVideoListRequest struct {
	UserId   int64 `path:"id"`
	PageNum  int32 `form:"page_num"`
	PageSize int32 `form:"page_size"`
}

type GetVideoListResponse struct {
	Base   BaseResponse    `json:"base"`
	Videos []VideoBaseinfo `json:"videos"`
	Total  int64           `json:"total"`
}

type Item struct {
	Videos        VideoBaseinfo `json:"videos"`
	VideosPopular VideoPopular  `json:"videos_popular"`
	Liked         bool          `json:"liked"`
	Favorited     bool          `json:"favorited"`
}

type LikeCommentRequest struct {
	CommentId int64 `path:"id"`
}

type LikeCommentResponse struct {
	Base BaseResponse `json:"base"`
}

type LikeVideoRequest struct {
	VideoId int64 `path:"id"`
}

type LikeVideoResponse struct {
	Base BaseResponse `json:"base"`
}

type LoginRequest struct {
	Username string `form:"username"`
	Password string `form:"password"`
	MfaCode  string `form:"mfa_code"`
}

type LoginResponse struct {
	Base         BaseResponse `json:"base"`
	UserID       int64        `json:"user_id,string"`
	AccessToken  string       `json:"-"`
	RefreshToken string       `json:"-"`
}

type PublishVideoRequest struct {
	Title       string `form:"title"`
	Description string `form:"description"`
	File        string `form:"file,optional"`
}

type PublishVideoResponse struct {
	Base    BaseResponse `json:"base"`
	VideoID int64        `json:"video_id,string"`
}

type RefreshTokenRequest struct {
	RefreshToken string `json:"-"`
}

type RefreshTokenResponse struct {
	Base         BaseResponse `json:"base"`
	AccessToken  string       `json:"-"`
	RefreshToken string       `json:"-"`
}

type RegisterRequest struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type RegisterResponse struct {
	Base   BaseResponse `json:"base"`
	UserID int64        `json:"user_id,string"`
}

type ReplyCommentRequest struct {
	CommentId   int64  `path:"id"`
	CommentText string `form:"comment_text"`
}

type ReplyCommentResponse struct {
	Base      BaseResponse `json:"base"`
	CommentID int64        `json:"comment_id,string"`
}

type SubscribeRequest struct {
	ToUserID int64 `path:"id"`
}

type SubscribeResponse struct {
	Base BaseResponse `json:"base"`
}

type UnsubscribeRequest struct {
	ToUserID int64 `path:"id"`
}

type UnsubscribeResponse struct {
	Base BaseResponse `json:"base"`
}

type UpdateUserPhotoRequest struct {
	File string `form:"file,optional"`
}

type UpdateUserPhotoResponse struct {
	Base     BaseResponse `json:"base"`
	PhotoURL string       `json:"photo_url"`
}

type UserBaseinfo struct {
	UserID    int64  `json:"user_id,string"`
	Username  string `json:"username"`
	Password  string `json:"password"`
	PhotoURL  string `json:"photo_url"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
	DeletedAt string `json:"deleted_at"`
}

type UserFollow struct {
	FollowerID int64 `json:"follower_id,string"`
	UserID     int64 `json:"user_id,string"`
	Status     int32 `json:"status"`
}

type VideoBaseinfo struct {
	VideoID     int64  `json:"video_id,string"`
	AuthorID    int64  `json:"author_id,string"`
	VideoURL    string `json:"video_url"`
	CoverURL    string `json:"cover_url"`
	Title       string `json:"title"`
	Description string `json:"description"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
	DeletedAt   string `json:"deleted_at"`
}

type VideoPopular struct {
	VideoID       int64 `json:"video_id,string"`
	VisitCount    int64 `json:"visit_count"`
	LikeCount     int64 `json:"like_count"`
	CommentCount  int64 `json:"comment_count"`
	FavoriteCount int64 `json:"favorite_count"`
}

type VideoPopularRequest struct {
	PageNum  int32 `form:"page_num"`
	PageSize int32 `form:"page_size"`
}

type VideoPopularResponse struct {
	Base  BaseResponse `json:"base"`
	Items []Item       `json:"items"`
}

type VideoSearchRequest struct {
	Keyword  string `form:"keyword"`
	PageNum  int32  `form:"page_num"`
	PageSize int32  `form:"page_size"`
}

type VideoSearchResponse struct {
	Base   BaseResponse    `json:"base"`
	Videos []VideoBaseinfo `json:"videos"`
}
