// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: app/video/rpc/video.proto

package video_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	VideoData     []byte                 `protobuf:"bytes,4,opt,name=video_data,json=videoData,proto3" json:"video_data,omitempty"`
	Filename      string                 `protobuf:"bytes,5,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishVideoRequest) Reset() {
	*x = PublishVideoRequest{}
	mi := &file_app_video_rpc_video_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishVideoRequest) ProtoMessage() {}

func (x *PublishVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_video_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishVideoRequest.ProtoReflect.Descriptor instead.
func (*PublishVideoRequest) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_video_proto_rawDescGZIP(), []int{0}
}

func (x *PublishVideoRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PublishVideoRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PublishVideoRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PublishVideoRequest) GetVideoData() []byte {
	if x != nil {
		return x.VideoData
	}
	return nil
}

func (x *PublishVideoRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type PublishVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       int64                  `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishVideoResponse) Reset() {
	*x = PublishVideoResponse{}
	mi := &file_app_video_rpc_video_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishVideoResponse) ProtoMessage() {}

func (x *PublishVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_video_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishVideoResponse.ProtoReflect.Descriptor instead.
func (*PublishVideoResponse) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_video_proto_rawDescGZIP(), []int{1}
}

func (x *PublishVideoResponse) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

type GetFeedVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastTime      string                 `protobuf:"bytes,1,opt,name=last_time,json=lastTime,proto3" json:"last_time,omitempty"`
	PageNum       int32                  `protobuf:"varint,2,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedVideoRequest) Reset() {
	*x = GetFeedVideoRequest{}
	mi := &file_app_video_rpc_video_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedVideoRequest) ProtoMessage() {}

func (x *GetFeedVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_video_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedVideoRequest.ProtoReflect.Descriptor instead.
func (*GetFeedVideoRequest) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_video_proto_rawDescGZIP(), []int{2}
}

func (x *GetFeedVideoRequest) GetLastTime() string {
	if x != nil {
		return x.LastTime
	}
	return ""
}

func (x *GetFeedVideoRequest) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *GetFeedVideoRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type VideoInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       int64                  `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	AuthorId      int64                  `protobuf:"varint,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	VideoUrl      string                 `protobuf:"bytes,3,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,4,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoInfo) Reset() {
	*x = VideoInfo{}
	mi := &file_app_video_rpc_video_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoInfo) ProtoMessage() {}

func (x *VideoInfo) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_video_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoInfo.ProtoReflect.Descriptor instead.
func (*VideoInfo) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_video_proto_rawDescGZIP(), []int{3}
}

func (x *VideoInfo) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *VideoInfo) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *VideoInfo) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *VideoInfo) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *VideoInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VideoInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *VideoInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetFeedVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Videos        []*VideoInfo           `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedVideoResponse) Reset() {
	*x = GetFeedVideoResponse{}
	mi := &file_app_video_rpc_video_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedVideoResponse) ProtoMessage() {}

func (x *GetFeedVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_video_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedVideoResponse.ProtoReflect.Descriptor instead.
func (*GetFeedVideoResponse) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_video_proto_rawDescGZIP(), []int{4}
}

func (x *GetFeedVideoResponse) GetVideos() []*VideoInfo {
	if x != nil {
		return x.Videos
	}
	return nil
}

func (x *GetFeedVideoResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetVideoListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      int64                  `protobuf:"varint,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	PageNum       int32                  `protobuf:"varint,2,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoListRequest) Reset() {
	*x = GetVideoListRequest{}
	mi := &file_app_video_rpc_video_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoListRequest) ProtoMessage() {}

func (x *GetVideoListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_video_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoListRequest.ProtoReflect.Descriptor instead.
func (*GetVideoListRequest) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_video_proto_rawDescGZIP(), []int{5}
}

func (x *GetVideoListRequest) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *GetVideoListRequest) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *GetVideoListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetVideoListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Videos        []*VideoInfo           `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoListResponse) Reset() {
	*x = GetVideoListResponse{}
	mi := &file_app_video_rpc_video_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoListResponse) ProtoMessage() {}

func (x *GetVideoListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_video_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoListResponse.ProtoReflect.Descriptor instead.
func (*GetVideoListResponse) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_video_proto_rawDescGZIP(), []int{6}
}

func (x *GetVideoListResponse) GetVideos() []*VideoInfo {
	if x != nil {
		return x.Videos
	}
	return nil
}

func (x *GetVideoListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type SearchVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	PageNum       int32                  `protobuf:"varint,2,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchVideoRequest) Reset() {
	*x = SearchVideoRequest{}
	mi := &file_app_video_rpc_video_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchVideoRequest) ProtoMessage() {}

func (x *SearchVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_video_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchVideoRequest.ProtoReflect.Descriptor instead.
func (*SearchVideoRequest) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_video_proto_rawDescGZIP(), []int{7}
}

func (x *SearchVideoRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchVideoRequest) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *SearchVideoRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Videos        []*VideoInfo           `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchVideoResponse) Reset() {
	*x = SearchVideoResponse{}
	mi := &file_app_video_rpc_video_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchVideoResponse) ProtoMessage() {}

func (x *SearchVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_video_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchVideoResponse.ProtoReflect.Descriptor instead.
func (*SearchVideoResponse) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_video_proto_rawDescGZIP(), []int{8}
}

func (x *SearchVideoResponse) GetVideos() []*VideoInfo {
	if x != nil {
		return x.Videos
	}
	return nil
}

func (x *SearchVideoResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetPopularVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageNum       int32                  `protobuf:"varint,1,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPopularVideoRequest) Reset() {
	*x = GetPopularVideoRequest{}
	mi := &file_app_video_rpc_video_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPopularVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPopularVideoRequest) ProtoMessage() {}

func (x *GetPopularVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_video_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPopularVideoRequest.ProtoReflect.Descriptor instead.
func (*GetPopularVideoRequest) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_video_proto_rawDescGZIP(), []int{9}
}

func (x *GetPopularVideoRequest) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *GetPopularVideoRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type VideoPopularInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       int64                  `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	VisitCount    int64                  `protobuf:"varint,2,opt,name=visit_count,json=visitCount,proto3" json:"visit_count,omitempty"`
	LikeCount     int64                  `protobuf:"varint,3,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	CommentCount  int64                  `protobuf:"varint,4,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	FavoriteCount int64                  `protobuf:"varint,5,opt,name=favorite_count,json=favoriteCount,proto3" json:"favorite_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoPopularInfo) Reset() {
	*x = VideoPopularInfo{}
	mi := &file_app_video_rpc_video_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoPopularInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoPopularInfo) ProtoMessage() {}

func (x *VideoPopularInfo) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_video_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoPopularInfo.ProtoReflect.Descriptor instead.
func (*VideoPopularInfo) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_video_proto_rawDescGZIP(), []int{10}
}

func (x *VideoPopularInfo) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *VideoPopularInfo) GetVisitCount() int64 {
	if x != nil {
		return x.VisitCount
	}
	return 0
}

func (x *VideoPopularInfo) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *VideoPopularInfo) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *VideoPopularInfo) GetFavoriteCount() int64 {
	if x != nil {
		return x.FavoriteCount
	}
	return 0
}

type GetPopularVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Videos        []*VideoInfo           `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	Populars      []*VideoPopularInfo    `protobuf:"bytes,2,rep,name=populars,proto3" json:"populars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPopularVideoResponse) Reset() {
	*x = GetPopularVideoResponse{}
	mi := &file_app_video_rpc_video_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPopularVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPopularVideoResponse) ProtoMessage() {}

func (x *GetPopularVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_video_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPopularVideoResponse.ProtoReflect.Descriptor instead.
func (*GetPopularVideoResponse) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_video_proto_rawDescGZIP(), []int{11}
}

func (x *GetPopularVideoResponse) GetVideos() []*VideoInfo {
	if x != nil {
		return x.Videos
	}
	return nil
}

func (x *GetPopularVideoResponse) GetPopulars() []*VideoPopularInfo {
	if x != nil {
		return x.Populars
	}
	return nil
}

type LikeVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VideoId       int64                  `protobuf:"varint,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	ActionType    int32                  `protobuf:"varint,3,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"` // 1-点赞 0-取消点赞
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeVideoRequest) Reset() {
	*x = LikeVideoRequest{}
	mi := &file_app_video_rpc_video_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeVideoRequest) ProtoMessage() {}

func (x *LikeVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_video_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeVideoRequest.ProtoReflect.Descriptor instead.
func (*LikeVideoRequest) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_video_proto_rawDescGZIP(), []int{12}
}

func (x *LikeVideoRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LikeVideoRequest) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *LikeVideoRequest) GetActionType() int32 {
	if x != nil {
		return x.ActionType
	}
	return 0
}

type LikeVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeVideoResponse) Reset() {
	*x = LikeVideoResponse{}
	mi := &file_app_video_rpc_video_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeVideoResponse) ProtoMessage() {}

func (x *LikeVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_video_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeVideoResponse.ProtoReflect.Descriptor instead.
func (*LikeVideoResponse) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_video_proto_rawDescGZIP(), []int{13}
}

type GetLikeListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PageNum       int32                  `protobuf:"varint,2,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLikeListRequest) Reset() {
	*x = GetLikeListRequest{}
	mi := &file_app_video_rpc_video_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLikeListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLikeListRequest) ProtoMessage() {}

func (x *GetLikeListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_video_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLikeListRequest.ProtoReflect.Descriptor instead.
func (*GetLikeListRequest) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_video_proto_rawDescGZIP(), []int{14}
}

func (x *GetLikeListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetLikeListRequest) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *GetLikeListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetLikeListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Videos        []*VideoInfo           `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLikeListResponse) Reset() {
	*x = GetLikeListResponse{}
	mi := &file_app_video_rpc_video_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLikeListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLikeListResponse) ProtoMessage() {}

func (x *GetLikeListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_video_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLikeListResponse.ProtoReflect.Descriptor instead.
func (*GetLikeListResponse) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_video_proto_rawDescGZIP(), []int{15}
}

func (x *GetLikeListResponse) GetVideos() []*VideoInfo {
	if x != nil {
		return x.Videos
	}
	return nil
}

func (x *GetLikeListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type FavoriteVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VideoId       int64                  `protobuf:"varint,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteVideoRequest) Reset() {
	*x = FavoriteVideoRequest{}
	mi := &file_app_video_rpc_video_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteVideoRequest) ProtoMessage() {}

func (x *FavoriteVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_video_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteVideoRequest.ProtoReflect.Descriptor instead.
func (*FavoriteVideoRequest) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_video_proto_rawDescGZIP(), []int{16}
}

func (x *FavoriteVideoRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FavoriteVideoRequest) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

type FavoriteVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteVideoResponse) Reset() {
	*x = FavoriteVideoResponse{}
	mi := &file_app_video_rpc_video_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteVideoResponse) ProtoMessage() {}

func (x *FavoriteVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_video_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteVideoResponse.ProtoReflect.Descriptor instead.
func (*FavoriteVideoResponse) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_video_proto_rawDescGZIP(), []int{17}
}

type CancelFavoriteVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VideoId       int64                  `protobuf:"varint,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelFavoriteVideoRequest) Reset() {
	*x = CancelFavoriteVideoRequest{}
	mi := &file_app_video_rpc_video_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelFavoriteVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelFavoriteVideoRequest) ProtoMessage() {}

func (x *CancelFavoriteVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_video_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelFavoriteVideoRequest.ProtoReflect.Descriptor instead.
func (*CancelFavoriteVideoRequest) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_video_proto_rawDescGZIP(), []int{18}
}

func (x *CancelFavoriteVideoRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CancelFavoriteVideoRequest) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

type CancelFavoriteVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelFavoriteVideoResponse) Reset() {
	*x = CancelFavoriteVideoResponse{}
	mi := &file_app_video_rpc_video_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelFavoriteVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelFavoriteVideoResponse) ProtoMessage() {}

func (x *CancelFavoriteVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_video_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelFavoriteVideoResponse.ProtoReflect.Descriptor instead.
func (*CancelFavoriteVideoResponse) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_video_proto_rawDescGZIP(), []int{19}
}

type GetFavoriteListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PageNum       int32                  `protobuf:"varint,2,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFavoriteListRequest) Reset() {
	*x = GetFavoriteListRequest{}
	mi := &file_app_video_rpc_video_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFavoriteListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFavoriteListRequest) ProtoMessage() {}

func (x *GetFavoriteListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_video_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFavoriteListRequest.ProtoReflect.Descriptor instead.
func (*GetFavoriteListRequest) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_video_proto_rawDescGZIP(), []int{20}
}

func (x *GetFavoriteListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetFavoriteListRequest) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *GetFavoriteListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetFavoriteListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Videos        []*VideoInfo           `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFavoriteListResponse) Reset() {
	*x = GetFavoriteListResponse{}
	mi := &file_app_video_rpc_video_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFavoriteListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFavoriteListResponse) ProtoMessage() {}

func (x *GetFavoriteListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_video_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFavoriteListResponse.ProtoReflect.Descriptor instead.
func (*GetFavoriteListResponse) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_video_proto_rawDescGZIP(), []int{21}
}

func (x *GetFavoriteListResponse) GetVideos() []*VideoInfo {
	if x != nil {
		return x.Videos
	}
	return nil
}

func (x *GetFavoriteListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type IncreaseVideoVisitCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       int64                  `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Delta         int64                  `protobuf:"varint,2,opt,name=delta,proto3" json:"delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncreaseVideoVisitCountRequest) Reset() {
	*x = IncreaseVideoVisitCountRequest{}
	mi := &file_app_video_rpc_video_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncreaseVideoVisitCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncreaseVideoVisitCountRequest) ProtoMessage() {}

func (x *IncreaseVideoVisitCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_video_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncreaseVideoVisitCountRequest.ProtoReflect.Descriptor instead.
func (*IncreaseVideoVisitCountRequest) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_video_proto_rawDescGZIP(), []int{22}
}

func (x *IncreaseVideoVisitCountRequest) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *IncreaseVideoVisitCountRequest) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

type IncreaseVideoVisitCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncreaseVideoVisitCountResponse) Reset() {
	*x = IncreaseVideoVisitCountResponse{}
	mi := &file_app_video_rpc_video_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncreaseVideoVisitCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncreaseVideoVisitCountResponse) ProtoMessage() {}

func (x *IncreaseVideoVisitCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_video_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncreaseVideoVisitCountResponse.ProtoReflect.Descriptor instead.
func (*IncreaseVideoVisitCountResponse) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_video_proto_rawDescGZIP(), []int{23}
}

var File_app_video_rpc_video_proto protoreflect.FileDescriptor

const file_app_video_rpc_video_proto_rawDesc = "" +
	"\n" +
	"\x19app/video/rpc/video.proto\x12\x05video\"\xa1\x01\n" +
	"\x13PublishVideoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"video_data\x18\x04 \x01(\fR\tvideoData\x12\x1a\n" +
	"\bfilename\x18\x05 \x01(\tR\bfilename\"1\n" +
	"\x14PublishVideoResponse\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x03R\avideoId\"j\n" +
	"\x13GetFeedVideoRequest\x12\x1b\n" +
	"\tlast_time\x18\x01 \x01(\tR\blastTime\x12\x19\n" +
	"\bpage_num\x18\x02 \x01(\x05R\apageNum\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\xd4\x01\n" +
	"\tVideoInfo\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x03R\avideoId\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\x03R\bauthorId\x12\x1b\n" +
	"\tvideo_url\x18\x03 \x01(\tR\bvideoUrl\x12\x1b\n" +
	"\tcover_url\x18\x04 \x01(\tR\bcoverUrl\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"V\n" +
	"\x14GetFeedVideoResponse\x12(\n" +
	"\x06videos\x18\x01 \x03(\v2\x10.video.VideoInfoR\x06videos\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"j\n" +
	"\x13GetVideoListRequest\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\x03R\bauthorId\x12\x19\n" +
	"\bpage_num\x18\x02 \x01(\x05R\apageNum\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"V\n" +
	"\x14GetVideoListResponse\x12(\n" +
	"\x06videos\x18\x01 \x03(\v2\x10.video.VideoInfoR\x06videos\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"f\n" +
	"\x12SearchVideoRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x19\n" +
	"\bpage_num\x18\x02 \x01(\x05R\apageNum\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"U\n" +
	"\x13SearchVideoResponse\x12(\n" +
	"\x06videos\x18\x01 \x03(\v2\x10.video.VideoInfoR\x06videos\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"P\n" +
	"\x16GetPopularVideoRequest\x12\x19\n" +
	"\bpage_num\x18\x01 \x01(\x05R\apageNum\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\xb9\x01\n" +
	"\x10VideoPopularInfo\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x03R\avideoId\x12\x1f\n" +
	"\vvisit_count\x18\x02 \x01(\x03R\n" +
	"visitCount\x12\x1d\n" +
	"\n" +
	"like_count\x18\x03 \x01(\x03R\tlikeCount\x12#\n" +
	"\rcomment_count\x18\x04 \x01(\x03R\fcommentCount\x12%\n" +
	"\x0efavorite_count\x18\x05 \x01(\x03R\rfavoriteCount\"x\n" +
	"\x17GetPopularVideoResponse\x12(\n" +
	"\x06videos\x18\x01 \x03(\v2\x10.video.VideoInfoR\x06videos\x123\n" +
	"\bpopulars\x18\x02 \x03(\v2\x17.video.VideoPopularInfoR\bpopulars\"g\n" +
	"\x10LikeVideoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\x03R\avideoId\x12\x1f\n" +
	"\vaction_type\x18\x03 \x01(\x05R\n" +
	"actionType\"\x13\n" +
	"\x11LikeVideoResponse\"e\n" +
	"\x12GetLikeListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\bpage_num\x18\x02 \x01(\x05R\apageNum\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"U\n" +
	"\x13GetLikeListResponse\x12(\n" +
	"\x06videos\x18\x01 \x03(\v2\x10.video.VideoInfoR\x06videos\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"J\n" +
	"\x14FavoriteVideoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\x03R\avideoId\"\x17\n" +
	"\x15FavoriteVideoResponse\"P\n" +
	"\x1aCancelFavoriteVideoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\x03R\avideoId\"\x1d\n" +
	"\x1bCancelFavoriteVideoResponse\"i\n" +
	"\x16GetFavoriteListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\bpage_num\x18\x02 \x01(\x05R\apageNum\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"Y\n" +
	"\x17GetFavoriteListResponse\x12(\n" +
	"\x06videos\x18\x01 \x03(\v2\x10.video.VideoInfoR\x06videos\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"Q\n" +
	"\x1eIncreaseVideoVisitCountRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x03R\avideoId\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\x03R\x05delta\"!\n" +
	"\x1fIncreaseVideoVisitCountResponse2\xed\x06\n" +
	"\fVideoService\x12G\n" +
	"\fPublishVideo\x12\x1a.video.PublishVideoRequest\x1a\x1b.video.PublishVideoResponse\x12G\n" +
	"\fGetFeedVideo\x12\x1a.video.GetFeedVideoRequest\x1a\x1b.video.GetFeedVideoResponse\x12G\n" +
	"\fGetVideoList\x12\x1a.video.GetVideoListRequest\x1a\x1b.video.GetVideoListResponse\x12D\n" +
	"\vSearchVideo\x12\x19.video.SearchVideoRequest\x1a\x1a.video.SearchVideoResponse\x12P\n" +
	"\x0fGetPopularVideo\x12\x1d.video.GetPopularVideoRequest\x1a\x1e.video.GetPopularVideoResponse\x12>\n" +
	"\tLikeVideo\x12\x17.video.LikeVideoRequest\x1a\x18.video.LikeVideoResponse\x12D\n" +
	"\vGetLikeList\x12\x19.video.GetLikeListRequest\x1a\x1a.video.GetLikeListResponse\x12J\n" +
	"\rFavoriteVideo\x12\x1b.video.FavoriteVideoRequest\x1a\x1c.video.FavoriteVideoResponse\x12\\\n" +
	"\x13CancelFavoriteVideo\x12!.video.CancelFavoriteVideoRequest\x1a\".video.CancelFavoriteVideoResponse\x12P\n" +
	"\x0fGetFavoriteList\x12\x1d.video.GetFavoriteListRequest\x1a\x1e.video.GetFavoriteListResponse\x12h\n" +
	"\x17IncreaseVideoVisitCount\x12%.video.IncreaseVideoVisitCountRequest\x1a&.video.IncreaseVideoVisitCountResponseB\fZ\n" +
	"./video_pbb\x06proto3"

var (
	file_app_video_rpc_video_proto_rawDescOnce sync.Once
	file_app_video_rpc_video_proto_rawDescData []byte
)

func file_app_video_rpc_video_proto_rawDescGZIP() []byte {
	file_app_video_rpc_video_proto_rawDescOnce.Do(func() {
		file_app_video_rpc_video_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_video_rpc_video_proto_rawDesc), len(file_app_video_rpc_video_proto_rawDesc)))
	})
	return file_app_video_rpc_video_proto_rawDescData
}

var file_app_video_rpc_video_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_app_video_rpc_video_proto_goTypes = []any{
	(*PublishVideoRequest)(nil),             // 0: video.PublishVideoRequest
	(*PublishVideoResponse)(nil),            // 1: video.PublishVideoResponse
	(*GetFeedVideoRequest)(nil),             // 2: video.GetFeedVideoRequest
	(*VideoInfo)(nil),                       // 3: video.VideoInfo
	(*GetFeedVideoResponse)(nil),            // 4: video.GetFeedVideoResponse
	(*GetVideoListRequest)(nil),             // 5: video.GetVideoListRequest
	(*GetVideoListResponse)(nil),            // 6: video.GetVideoListResponse
	(*SearchVideoRequest)(nil),              // 7: video.SearchVideoRequest
	(*SearchVideoResponse)(nil),             // 8: video.SearchVideoResponse
	(*GetPopularVideoRequest)(nil),          // 9: video.GetPopularVideoRequest
	(*VideoPopularInfo)(nil),                // 10: video.VideoPopularInfo
	(*GetPopularVideoResponse)(nil),         // 11: video.GetPopularVideoResponse
	(*LikeVideoRequest)(nil),                // 12: video.LikeVideoRequest
	(*LikeVideoResponse)(nil),               // 13: video.LikeVideoResponse
	(*GetLikeListRequest)(nil),              // 14: video.GetLikeListRequest
	(*GetLikeListResponse)(nil),             // 15: video.GetLikeListResponse
	(*FavoriteVideoRequest)(nil),            // 16: video.FavoriteVideoRequest
	(*FavoriteVideoResponse)(nil),           // 17: video.FavoriteVideoResponse
	(*CancelFavoriteVideoRequest)(nil),      // 18: video.CancelFavoriteVideoRequest
	(*CancelFavoriteVideoResponse)(nil),     // 19: video.CancelFavoriteVideoResponse
	(*GetFavoriteListRequest)(nil),          // 20: video.GetFavoriteListRequest
	(*GetFavoriteListResponse)(nil),         // 21: video.GetFavoriteListResponse
	(*IncreaseVideoVisitCountRequest)(nil),  // 22: video.IncreaseVideoVisitCountRequest
	(*IncreaseVideoVisitCountResponse)(nil), // 23: video.IncreaseVideoVisitCountResponse
}
var file_app_video_rpc_video_proto_depIdxs = []int32{
	3,  // 0: video.GetFeedVideoResponse.videos:type_name -> video.VideoInfo
	3,  // 1: video.GetVideoListResponse.videos:type_name -> video.VideoInfo
	3,  // 2: video.SearchVideoResponse.videos:type_name -> video.VideoInfo
	3,  // 3: video.GetPopularVideoResponse.videos:type_name -> video.VideoInfo
	10, // 4: video.GetPopularVideoResponse.populars:type_name -> video.VideoPopularInfo
	3,  // 5: video.GetLikeListResponse.videos:type_name -> video.VideoInfo
	3,  // 6: video.GetFavoriteListResponse.videos:type_name -> video.VideoInfo
	0,  // 7: video.VideoService.PublishVideo:input_type -> video.PublishVideoRequest
	2,  // 8: video.VideoService.GetFeedVideo:input_type -> video.GetFeedVideoRequest
	5,  // 9: video.VideoService.GetVideoList:input_type -> video.GetVideoListRequest
	7,  // 10: video.VideoService.SearchVideo:input_type -> video.SearchVideoRequest
	9,  // 11: video.VideoService.GetPopularVideo:input_type -> video.GetPopularVideoRequest
	12, // 12: video.VideoService.LikeVideo:input_type -> video.LikeVideoRequest
	14, // 13: video.VideoService.GetLikeList:input_type -> video.GetLikeListRequest
	16, // 14: video.VideoService.FavoriteVideo:input_type -> video.FavoriteVideoRequest
	18, // 15: video.VideoService.CancelFavoriteVideo:input_type -> video.CancelFavoriteVideoRequest
	20, // 16: video.VideoService.GetFavoriteList:input_type -> video.GetFavoriteListRequest
	22, // 17: video.VideoService.IncreaseVideoVisitCount:input_type -> video.IncreaseVideoVisitCountRequest
	1,  // 18: video.VideoService.PublishVideo:output_type -> video.PublishVideoResponse
	4,  // 19: video.VideoService.GetFeedVideo:output_type -> video.GetFeedVideoResponse
	6,  // 20: video.VideoService.GetVideoList:output_type -> video.GetVideoListResponse
	8,  // 21: video.VideoService.SearchVideo:output_type -> video.SearchVideoResponse
	11, // 22: video.VideoService.GetPopularVideo:output_type -> video.GetPopularVideoResponse
	13, // 23: video.VideoService.LikeVideo:output_type -> video.LikeVideoResponse
	15, // 24: video.VideoService.GetLikeList:output_type -> video.GetLikeListResponse
	17, // 25: video.VideoService.FavoriteVideo:output_type -> video.FavoriteVideoResponse
	19, // 26: video.VideoService.CancelFavoriteVideo:output_type -> video.CancelFavoriteVideoResponse
	21, // 27: video.VideoService.GetFavoriteList:output_type -> video.GetFavoriteListResponse
	23, // 28: video.VideoService.IncreaseVideoVisitCount:output_type -> video.IncreaseVideoVisitCountResponse
	18, // [18:29] is the sub-list for method output_type
	7,  // [7:18] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_app_video_rpc_video_proto_init() }
func file_app_video_rpc_video_proto_init() {
	if File_app_video_rpc_video_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_video_rpc_video_proto_rawDesc), len(file_app_video_rpc_video_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_video_rpc_video_proto_goTypes,
		DependencyIndexes: file_app_video_rpc_video_proto_depIdxs,
		MessageInfos:      file_app_video_rpc_video_proto_msgTypes,
	}.Build()
	File_app_video_rpc_video_proto = out.File
	file_app_video_rpc_video_proto_goTypes = nil
	file_app_video_rpc_video_proto_depIdxs = nil
}
