// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: app/video/rpc/video.proto

package video_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	VideoData     []byte                 `protobuf:"bytes,4,opt,name=video_data,json=videoData,proto3" json:"video_data,omitempty"`
	Filename      string                 `protobuf:"bytes,5,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishVideoRequest) Reset() {
	*x = PublishVideoRequest{}
	mi := &file_app_video_rpc_video_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishVideoRequest) ProtoMessage() {}

func (x *PublishVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_video_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishVideoRequest.ProtoReflect.Descriptor instead.
func (*PublishVideoRequest) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_video_proto_rawDescGZIP(), []int{0}
}

func (x *PublishVideoRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PublishVideoRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PublishVideoRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PublishVideoRequest) GetVideoData() []byte {
	if x != nil {
		return x.VideoData
	}
	return nil
}

func (x *PublishVideoRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type PublishVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       int64                  `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishVideoResponse) Reset() {
	*x = PublishVideoResponse{}
	mi := &file_app_video_rpc_video_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishVideoResponse) ProtoMessage() {}

func (x *PublishVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_video_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishVideoResponse.ProtoReflect.Descriptor instead.
func (*PublishVideoResponse) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_video_proto_rawDescGZIP(), []int{1}
}

func (x *PublishVideoResponse) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

type GetFeedVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastTime      string                 `protobuf:"bytes,1,opt,name=last_time,json=lastTime,proto3" json:"last_time,omitempty"`
	PageNum       int32                  `protobuf:"varint,2,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedVideoRequest) Reset() {
	*x = GetFeedVideoRequest{}
	mi := &file_app_video_rpc_video_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedVideoRequest) ProtoMessage() {}

func (x *GetFeedVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_video_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedVideoRequest.ProtoReflect.Descriptor instead.
func (*GetFeedVideoRequest) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_video_proto_rawDescGZIP(), []int{2}
}

func (x *GetFeedVideoRequest) GetLastTime() string {
	if x != nil {
		return x.LastTime
	}
	return ""
}

func (x *GetFeedVideoRequest) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *GetFeedVideoRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type VideoInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       int64                  `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	AuthorId      int64                  `protobuf:"varint,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	VideoUrl      string                 `protobuf:"bytes,3,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,4,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoInfo) Reset() {
	*x = VideoInfo{}
	mi := &file_app_video_rpc_video_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoInfo) ProtoMessage() {}

func (x *VideoInfo) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_video_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoInfo.ProtoReflect.Descriptor instead.
func (*VideoInfo) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_video_proto_rawDescGZIP(), []int{3}
}

func (x *VideoInfo) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *VideoInfo) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *VideoInfo) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *VideoInfo) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *VideoInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VideoInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *VideoInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetFeedVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Videos        []*VideoInfo           `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedVideoResponse) Reset() {
	*x = GetFeedVideoResponse{}
	mi := &file_app_video_rpc_video_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedVideoResponse) ProtoMessage() {}

func (x *GetFeedVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_video_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedVideoResponse.ProtoReflect.Descriptor instead.
func (*GetFeedVideoResponse) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_video_proto_rawDescGZIP(), []int{4}
}

func (x *GetFeedVideoResponse) GetVideos() []*VideoInfo {
	if x != nil {
		return x.Videos
	}
	return nil
}

func (x *GetFeedVideoResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetVideoListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      int64                  `protobuf:"varint,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	PageNum       int32                  `protobuf:"varint,2,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoListRequest) Reset() {
	*x = GetVideoListRequest{}
	mi := &file_app_video_rpc_video_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoListRequest) ProtoMessage() {}

func (x *GetVideoListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_video_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoListRequest.ProtoReflect.Descriptor instead.
func (*GetVideoListRequest) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_video_proto_rawDescGZIP(), []int{5}
}

func (x *GetVideoListRequest) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *GetVideoListRequest) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *GetVideoListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetVideoListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Videos        []*VideoInfo           `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoListResponse) Reset() {
	*x = GetVideoListResponse{}
	mi := &file_app_video_rpc_video_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoListResponse) ProtoMessage() {}

func (x *GetVideoListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_video_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoListResponse.ProtoReflect.Descriptor instead.
func (*GetVideoListResponse) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_video_proto_rawDescGZIP(), []int{6}
}

func (x *GetVideoListResponse) GetVideos() []*VideoInfo {
	if x != nil {
		return x.Videos
	}
	return nil
}

func (x *GetVideoListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type SearchVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	PageNum       int32                  `protobuf:"varint,2,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchVideoRequest) Reset() {
	*x = SearchVideoRequest{}
	mi := &file_app_video_rpc_video_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchVideoRequest) ProtoMessage() {}

func (x *SearchVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_video_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchVideoRequest.ProtoReflect.Descriptor instead.
func (*SearchVideoRequest) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_video_proto_rawDescGZIP(), []int{7}
}

func (x *SearchVideoRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchVideoRequest) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *SearchVideoRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Videos        []*VideoInfo           `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchVideoResponse) Reset() {
	*x = SearchVideoResponse{}
	mi := &file_app_video_rpc_video_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchVideoResponse) ProtoMessage() {}

func (x *SearchVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_video_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchVideoResponse.ProtoReflect.Descriptor instead.
func (*SearchVideoResponse) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_video_proto_rawDescGZIP(), []int{8}
}

func (x *SearchVideoResponse) GetVideos() []*VideoInfo {
	if x != nil {
		return x.Videos
	}
	return nil
}

func (x *SearchVideoResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetVideosByIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoIds      []int64                `protobuf:"varint,1,rep,packed,name=video_ids,json=videoIds,proto3" json:"video_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideosByIDsRequest) Reset() {
	*x = GetVideosByIDsRequest{}
	mi := &file_app_video_rpc_video_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideosByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideosByIDsRequest) ProtoMessage() {}

func (x *GetVideosByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_video_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideosByIDsRequest.ProtoReflect.Descriptor instead.
func (*GetVideosByIDsRequest) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_video_proto_rawDescGZIP(), []int{9}
}

func (x *GetVideosByIDsRequest) GetVideoIds() []int64 {
	if x != nil {
		return x.VideoIds
	}
	return nil
}

type GetVideosByIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Videos        []*VideoInfo           `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideosByIDsResponse) Reset() {
	*x = GetVideosByIDsResponse{}
	mi := &file_app_video_rpc_video_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideosByIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideosByIDsResponse) ProtoMessage() {}

func (x *GetVideosByIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_video_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideosByIDsResponse.ProtoReflect.Descriptor instead.
func (*GetVideosByIDsResponse) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_video_proto_rawDescGZIP(), []int{10}
}

func (x *GetVideosByIDsResponse) GetVideos() []*VideoInfo {
	if x != nil {
		return x.Videos
	}
	return nil
}

type GetPopularVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageNum       int32                  `protobuf:"varint,1,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPopularVideoRequest) Reset() {
	*x = GetPopularVideoRequest{}
	mi := &file_app_video_rpc_video_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPopularVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPopularVideoRequest) ProtoMessage() {}

func (x *GetPopularVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_video_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPopularVideoRequest.ProtoReflect.Descriptor instead.
func (*GetPopularVideoRequest) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_video_proto_rawDescGZIP(), []int{11}
}

func (x *GetPopularVideoRequest) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *GetPopularVideoRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type VideoPopularInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       int64                  `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	VisitCount    int64                  `protobuf:"varint,2,opt,name=visit_count,json=visitCount,proto3" json:"visit_count,omitempty"`
	LikeCount     int64                  `protobuf:"varint,3,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	CommentCount  int64                  `protobuf:"varint,4,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	FavoriteCount int64                  `protobuf:"varint,5,opt,name=favorite_count,json=favoriteCount,proto3" json:"favorite_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoPopularInfo) Reset() {
	*x = VideoPopularInfo{}
	mi := &file_app_video_rpc_video_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoPopularInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoPopularInfo) ProtoMessage() {}

func (x *VideoPopularInfo) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_video_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoPopularInfo.ProtoReflect.Descriptor instead.
func (*VideoPopularInfo) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_video_proto_rawDescGZIP(), []int{12}
}

func (x *VideoPopularInfo) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *VideoPopularInfo) GetVisitCount() int64 {
	if x != nil {
		return x.VisitCount
	}
	return 0
}

func (x *VideoPopularInfo) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *VideoPopularInfo) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *VideoPopularInfo) GetFavoriteCount() int64 {
	if x != nil {
		return x.FavoriteCount
	}
	return 0
}

type GetPopularVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Videos        []*VideoInfo           `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	Populars      []*VideoPopularInfo    `protobuf:"bytes,2,rep,name=populars,proto3" json:"populars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPopularVideoResponse) Reset() {
	*x = GetPopularVideoResponse{}
	mi := &file_app_video_rpc_video_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPopularVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPopularVideoResponse) ProtoMessage() {}

func (x *GetPopularVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_video_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPopularVideoResponse.ProtoReflect.Descriptor instead.
func (*GetPopularVideoResponse) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_video_proto_rawDescGZIP(), []int{13}
}

func (x *GetPopularVideoResponse) GetVideos() []*VideoInfo {
	if x != nil {
		return x.Videos
	}
	return nil
}

func (x *GetPopularVideoResponse) GetPopulars() []*VideoPopularInfo {
	if x != nil {
		return x.Populars
	}
	return nil
}

type IncreaseVideoVisitCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       int64                  `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Delta         int64                  `protobuf:"varint,2,opt,name=delta,proto3" json:"delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncreaseVideoVisitCountRequest) Reset() {
	*x = IncreaseVideoVisitCountRequest{}
	mi := &file_app_video_rpc_video_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncreaseVideoVisitCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncreaseVideoVisitCountRequest) ProtoMessage() {}

func (x *IncreaseVideoVisitCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_video_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncreaseVideoVisitCountRequest.ProtoReflect.Descriptor instead.
func (*IncreaseVideoVisitCountRequest) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_video_proto_rawDescGZIP(), []int{14}
}

func (x *IncreaseVideoVisitCountRequest) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *IncreaseVideoVisitCountRequest) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

type IncreaseVideoVisitCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncreaseVideoVisitCountResponse) Reset() {
	*x = IncreaseVideoVisitCountResponse{}
	mi := &file_app_video_rpc_video_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncreaseVideoVisitCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncreaseVideoVisitCountResponse) ProtoMessage() {}

func (x *IncreaseVideoVisitCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_video_rpc_video_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncreaseVideoVisitCountResponse.ProtoReflect.Descriptor instead.
func (*IncreaseVideoVisitCountResponse) Descriptor() ([]byte, []int) {
	return file_app_video_rpc_video_proto_rawDescGZIP(), []int{15}
}

var File_app_video_rpc_video_proto protoreflect.FileDescriptor

const file_app_video_rpc_video_proto_rawDesc = "" +
	"\n" +
	"\x19app/video/rpc/video.proto\x12\x05video\"\xa1\x01\n" +
	"\x13PublishVideoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"video_data\x18\x04 \x01(\fR\tvideoData\x12\x1a\n" +
	"\bfilename\x18\x05 \x01(\tR\bfilename\"1\n" +
	"\x14PublishVideoResponse\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x03R\avideoId\"j\n" +
	"\x13GetFeedVideoRequest\x12\x1b\n" +
	"\tlast_time\x18\x01 \x01(\tR\blastTime\x12\x19\n" +
	"\bpage_num\x18\x02 \x01(\x05R\apageNum\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\xd4\x01\n" +
	"\tVideoInfo\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x03R\avideoId\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\x03R\bauthorId\x12\x1b\n" +
	"\tvideo_url\x18\x03 \x01(\tR\bvideoUrl\x12\x1b\n" +
	"\tcover_url\x18\x04 \x01(\tR\bcoverUrl\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"V\n" +
	"\x14GetFeedVideoResponse\x12(\n" +
	"\x06videos\x18\x01 \x03(\v2\x10.video.VideoInfoR\x06videos\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"j\n" +
	"\x13GetVideoListRequest\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\x03R\bauthorId\x12\x19\n" +
	"\bpage_num\x18\x02 \x01(\x05R\apageNum\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"V\n" +
	"\x14GetVideoListResponse\x12(\n" +
	"\x06videos\x18\x01 \x03(\v2\x10.video.VideoInfoR\x06videos\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"f\n" +
	"\x12SearchVideoRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x19\n" +
	"\bpage_num\x18\x02 \x01(\x05R\apageNum\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"U\n" +
	"\x13SearchVideoResponse\x12(\n" +
	"\x06videos\x18\x01 \x03(\v2\x10.video.VideoInfoR\x06videos\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"4\n" +
	"\x15GetVideosByIDsRequest\x12\x1b\n" +
	"\tvideo_ids\x18\x01 \x03(\x03R\bvideoIds\"B\n" +
	"\x16GetVideosByIDsResponse\x12(\n" +
	"\x06videos\x18\x01 \x03(\v2\x10.video.VideoInfoR\x06videos\"P\n" +
	"\x16GetPopularVideoRequest\x12\x19\n" +
	"\bpage_num\x18\x01 \x01(\x05R\apageNum\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\xb9\x01\n" +
	"\x10VideoPopularInfo\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x03R\avideoId\x12\x1f\n" +
	"\vvisit_count\x18\x02 \x01(\x03R\n" +
	"visitCount\x12\x1d\n" +
	"\n" +
	"like_count\x18\x03 \x01(\x03R\tlikeCount\x12#\n" +
	"\rcomment_count\x18\x04 \x01(\x03R\fcommentCount\x12%\n" +
	"\x0efavorite_count\x18\x05 \x01(\x03R\rfavoriteCount\"x\n" +
	"\x17GetPopularVideoResponse\x12(\n" +
	"\x06videos\x18\x01 \x03(\v2\x10.video.VideoInfoR\x06videos\x123\n" +
	"\bpopulars\x18\x02 \x03(\v2\x17.video.VideoPopularInfoR\bpopulars\"Q\n" +
	"\x1eIncreaseVideoVisitCountRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x03R\avideoId\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\x03R\x05delta\"!\n" +
	"\x1fIncreaseVideoVisitCountResponse2\xba\x04\n" +
	"\fVideoService\x12G\n" +
	"\fPublishVideo\x12\x1a.video.PublishVideoRequest\x1a\x1b.video.PublishVideoResponse\x12G\n" +
	"\fGetFeedVideo\x12\x1a.video.GetFeedVideoRequest\x1a\x1b.video.GetFeedVideoResponse\x12G\n" +
	"\fGetVideoList\x12\x1a.video.GetVideoListRequest\x1a\x1b.video.GetVideoListResponse\x12D\n" +
	"\vSearchVideo\x12\x19.video.SearchVideoRequest\x1a\x1a.video.SearchVideoResponse\x12P\n" +
	"\x0fGetPopularVideo\x12\x1d.video.GetPopularVideoRequest\x1a\x1e.video.GetPopularVideoResponse\x12M\n" +
	"\x0eGetVideosByIDs\x12\x1c.video.GetVideosByIDsRequest\x1a\x1d.video.GetVideosByIDsResponse\x12h\n" +
	"\x17IncreaseVideoVisitCount\x12%.video.IncreaseVideoVisitCountRequest\x1a&.video.IncreaseVideoVisitCountResponseB\fZ\n" +
	"./video_pbb\x06proto3"

var (
	file_app_video_rpc_video_proto_rawDescOnce sync.Once
	file_app_video_rpc_video_proto_rawDescData []byte
)

func file_app_video_rpc_video_proto_rawDescGZIP() []byte {
	file_app_video_rpc_video_proto_rawDescOnce.Do(func() {
		file_app_video_rpc_video_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_video_rpc_video_proto_rawDesc), len(file_app_video_rpc_video_proto_rawDesc)))
	})
	return file_app_video_rpc_video_proto_rawDescData
}

var file_app_video_rpc_video_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_app_video_rpc_video_proto_goTypes = []any{
	(*PublishVideoRequest)(nil),             // 0: video.PublishVideoRequest
	(*PublishVideoResponse)(nil),            // 1: video.PublishVideoResponse
	(*GetFeedVideoRequest)(nil),             // 2: video.GetFeedVideoRequest
	(*VideoInfo)(nil),                       // 3: video.VideoInfo
	(*GetFeedVideoResponse)(nil),            // 4: video.GetFeedVideoResponse
	(*GetVideoListRequest)(nil),             // 5: video.GetVideoListRequest
	(*GetVideoListResponse)(nil),            // 6: video.GetVideoListResponse
	(*SearchVideoRequest)(nil),              // 7: video.SearchVideoRequest
	(*SearchVideoResponse)(nil),             // 8: video.SearchVideoResponse
	(*GetVideosByIDsRequest)(nil),           // 9: video.GetVideosByIDsRequest
	(*GetVideosByIDsResponse)(nil),          // 10: video.GetVideosByIDsResponse
	(*GetPopularVideoRequest)(nil),          // 11: video.GetPopularVideoRequest
	(*VideoPopularInfo)(nil),                // 12: video.VideoPopularInfo
	(*GetPopularVideoResponse)(nil),         // 13: video.GetPopularVideoResponse
	(*IncreaseVideoVisitCountRequest)(nil),  // 14: video.IncreaseVideoVisitCountRequest
	(*IncreaseVideoVisitCountResponse)(nil), // 15: video.IncreaseVideoVisitCountResponse
}
var file_app_video_rpc_video_proto_depIdxs = []int32{
	3,  // 0: video.GetFeedVideoResponse.videos:type_name -> video.VideoInfo
	3,  // 1: video.GetVideoListResponse.videos:type_name -> video.VideoInfo
	3,  // 2: video.SearchVideoResponse.videos:type_name -> video.VideoInfo
	3,  // 3: video.GetVideosByIDsResponse.videos:type_name -> video.VideoInfo
	3,  // 4: video.GetPopularVideoResponse.videos:type_name -> video.VideoInfo
	12, // 5: video.GetPopularVideoResponse.populars:type_name -> video.VideoPopularInfo
	0,  // 6: video.VideoService.PublishVideo:input_type -> video.PublishVideoRequest
	2,  // 7: video.VideoService.GetFeedVideo:input_type -> video.GetFeedVideoRequest
	5,  // 8: video.VideoService.GetVideoList:input_type -> video.GetVideoListRequest
	7,  // 9: video.VideoService.SearchVideo:input_type -> video.SearchVideoRequest
	11, // 10: video.VideoService.GetPopularVideo:input_type -> video.GetPopularVideoRequest
	9,  // 11: video.VideoService.GetVideosByIDs:input_type -> video.GetVideosByIDsRequest
	14, // 12: video.VideoService.IncreaseVideoVisitCount:input_type -> video.IncreaseVideoVisitCountRequest
	1,  // 13: video.VideoService.PublishVideo:output_type -> video.PublishVideoResponse
	4,  // 14: video.VideoService.GetFeedVideo:output_type -> video.GetFeedVideoResponse
	6,  // 15: video.VideoService.GetVideoList:output_type -> video.GetVideoListResponse
	8,  // 16: video.VideoService.SearchVideo:output_type -> video.SearchVideoResponse
	13, // 17: video.VideoService.GetPopularVideo:output_type -> video.GetPopularVideoResponse
	10, // 18: video.VideoService.GetVideosByIDs:output_type -> video.GetVideosByIDsResponse
	15, // 19: video.VideoService.IncreaseVideoVisitCount:output_type -> video.IncreaseVideoVisitCountResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_app_video_rpc_video_proto_init() }
func file_app_video_rpc_video_proto_init() {
	if File_app_video_rpc_video_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_video_rpc_video_proto_rawDesc), len(file_app_video_rpc_video_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_video_rpc_video_proto_goTypes,
		DependencyIndexes: file_app_video_rpc_video_proto_depIdxs,
		MessageInfos:      file_app_video_rpc_video_proto_msgTypes,
	}.Build()
	File_app_video_rpc_video_proto = out.File
	file_app_video_rpc_video_proto_goTypes = nil
	file_app_video_rpc_video_proto_depIdxs = nil
}
