// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type BaseResponse struct {
	StatusCode int32  `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
}

type BindMfaqrcodeRequest struct {
	Mfa_secret string `form:"mfa_secret"`
	Mfa_code   string `form:"mfa_code"`
}

type BindMfaqrcodeResponse struct {
	Base BaseResponse `json:"base"`
}

type JwchGetUserCookieRequest struct {
}

type JwchGetUserCookieResponse struct {
	Base   BaseResponse `json:"base"`
	JwchID string       `json:"jwch_id"`
	Cookie string       `json:"cookie" `
}

type JwchLoginRequest struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type JwchLoginResponse struct {
	Base BaseResponse `json:"base"`
}

type LoginRequest struct {
	Username string `form:"username"`
	Password string `form:"password"`
	MfaCode  string `form:"mfa_code"`
}

type LoginResponse struct {
	Base         BaseResponse `json:"base"`
	UserID       string       `json:"user_id"`
	AccessToken  string       `json:"access_token"`
	RefreshToken string       `json:"refresh_token" cookie:"refresh_token"`
}

type MfaqrcodeRequest struct {
	Mfa_ticket string `form:"mfa_ticket"`
}

type MfaqrcodeResponse struct {
	Base       BaseResponse `json:"base"`
	QRCodeURL  string       `json:"qr_code"`
	Mfa_secret string       `json:"mfa_secret"`
}

type RefreshTokenRequest struct {
	RefreshToken string `cookie:"refresh_token"`
}

type RefreshTokenResponse struct {
	Base         BaseResponse `json:"base"`
	AccessToken  string       `json:"access_token"`
	RefreshToken string       `json:"refresh_token" cookie:"refresh_token"`
}

type RegisterRequest struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type RegisterResponse struct {
	Base   BaseResponse `json:"base"`
	UserID string       `json:"user_id"`
}

type UserBaseinfo struct {
	UserID    string `json:"user_id"`
	Username  string `json:"username"`
	Password  string `json:"password"`
	PhotoURL  string `json:"photo_url"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
	DeletedAt string `json:"deleted_at"`
}

type UserFollow struct {
	FollowerID string `json:"follower_id"`
	UserID     string `json:"user_id"`
	Status     int32  `json:"status"`
}

type UserInfoRequest struct {
	UserID string `form:"user_id"`
}

type UserInfoResponse struct {
	Base BaseResponse `json:"base"`
	User UserBaseinfo `json:"user"`
}

type User_mfa struct {
	UserID             string `json:"user_id"`
	MFASecret          string `json:"mfa_secret"`
	MFAEnabled         bool   `json:"mfa_enabled"`
	PasswordHash       string `json:"password_hash"`
	MFA_Pending_secret string `json:"mfa_pending_secret"`
}

type UserphotoRequest struct {
	PhotoURL string `form:"photo_url"`
}

type UserphotoResponse struct {
	StatusCode int32  `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
}
