// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: video.proto

package videoservice

import (
	"context"

	"go_zero-tiktok/app/video/rpc/video_pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetFeedVideoRequest             = video_pb.GetFeedVideoRequest
	GetFeedVideoResponse            = video_pb.GetFeedVideoResponse
	GetPopularVideoRequest          = video_pb.GetPopularVideoRequest
	GetPopularVideoResponse         = video_pb.GetPopularVideoResponse
	GetVideoListRequest             = video_pb.GetVideoListRequest
	GetVideoListResponse            = video_pb.GetVideoListResponse
	GetVideosByIDsRequest           = video_pb.GetVideosByIDsRequest
	GetVideosByIDsResponse          = video_pb.GetVideosByIDsResponse
	IncreaseVideoVisitCountRequest  = video_pb.IncreaseVideoVisitCountRequest
	IncreaseVideoVisitCountResponse = video_pb.IncreaseVideoVisitCountResponse
	PublishVideoRequest             = video_pb.PublishVideoRequest
	PublishVideoResponse            = video_pb.PublishVideoResponse
	SearchVideoRequest              = video_pb.SearchVideoRequest
	SearchVideoResponse             = video_pb.SearchVideoResponse
	VideoInfo                       = video_pb.VideoInfo
	VideoPopularInfo                = video_pb.VideoPopularInfo

	VideoService interface {
		PublishVideo(ctx context.Context, in *PublishVideoRequest, opts ...grpc.CallOption) (*PublishVideoResponse, error)
		GetFeedVideo(ctx context.Context, in *GetFeedVideoRequest, opts ...grpc.CallOption) (*GetFeedVideoResponse, error)
		GetVideoList(ctx context.Context, in *GetVideoListRequest, opts ...grpc.CallOption) (*GetVideoListResponse, error)
		SearchVideo(ctx context.Context, in *SearchVideoRequest, opts ...grpc.CallOption) (*SearchVideoResponse, error)
		GetPopularVideo(ctx context.Context, in *GetPopularVideoRequest, opts ...grpc.CallOption) (*GetPopularVideoResponse, error)
		GetVideosByIDs(ctx context.Context, in *GetVideosByIDsRequest, opts ...grpc.CallOption) (*GetVideosByIDsResponse, error)
		IncreaseVideoVisitCount(ctx context.Context, in *IncreaseVideoVisitCountRequest, opts ...grpc.CallOption) (*IncreaseVideoVisitCountResponse, error)
	}

	defaultVideoService struct {
		cli zrpc.Client
	}
)

func NewVideoService(cli zrpc.Client) VideoService {
	return &defaultVideoService{
		cli: cli,
	}
}

func (m *defaultVideoService) PublishVideo(ctx context.Context, in *PublishVideoRequest, opts ...grpc.CallOption) (*PublishVideoResponse, error) {
	client := video_pb.NewVideoServiceClient(m.cli.Conn())
	return client.PublishVideo(ctx, in, opts...)
}

func (m *defaultVideoService) GetFeedVideo(ctx context.Context, in *GetFeedVideoRequest, opts ...grpc.CallOption) (*GetFeedVideoResponse, error) {
	client := video_pb.NewVideoServiceClient(m.cli.Conn())
	return client.GetFeedVideo(ctx, in, opts...)
}

func (m *defaultVideoService) GetVideoList(ctx context.Context, in *GetVideoListRequest, opts ...grpc.CallOption) (*GetVideoListResponse, error) {
	client := video_pb.NewVideoServiceClient(m.cli.Conn())
	return client.GetVideoList(ctx, in, opts...)
}

func (m *defaultVideoService) SearchVideo(ctx context.Context, in *SearchVideoRequest, opts ...grpc.CallOption) (*SearchVideoResponse, error) {
	client := video_pb.NewVideoServiceClient(m.cli.Conn())
	return client.SearchVideo(ctx, in, opts...)
}

func (m *defaultVideoService) GetPopularVideo(ctx context.Context, in *GetPopularVideoRequest, opts ...grpc.CallOption) (*GetPopularVideoResponse, error) {
	client := video_pb.NewVideoServiceClient(m.cli.Conn())
	return client.GetPopularVideo(ctx, in, opts...)
}

func (m *defaultVideoService) GetVideosByIDs(ctx context.Context, in *GetVideosByIDsRequest, opts ...grpc.CallOption) (*GetVideosByIDsResponse, error) {
	client := video_pb.NewVideoServiceClient(m.cli.Conn())
	return client.GetVideosByIDs(ctx, in, opts...)
}

func (m *defaultVideoService) IncreaseVideoVisitCount(ctx context.Context, in *IncreaseVideoVisitCountRequest, opts ...grpc.CallOption) (*IncreaseVideoVisitCountResponse, error) {
	client := video_pb.NewVideoServiceClient(m.cli.Conn())
	return client.IncreaseVideoVisitCount(ctx, in, opts...)
}
