// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: video.proto

package videoservice

import (
	"context"

	"go_zero-tiktok/app/video/rpc/video_pb/video_pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetFeedVideoRequest     = video_pb.GetFeedVideoRequest
	GetFeedVideoResponse    = video_pb.GetFeedVideoResponse
	GetLikeListRequest      = video_pb.GetLikeListRequest
	GetLikeListResponse     = video_pb.GetLikeListResponse
	GetPopularVideoRequest  = video_pb.GetPopularVideoRequest
	GetPopularVideoResponse = video_pb.GetPopularVideoResponse
	GetVideoListRequest     = video_pb.GetVideoListRequest
	GetVideoListResponse    = video_pb.GetVideoListResponse
	LikeVideoRequest        = video_pb.LikeVideoRequest
	LikeVideoResponse       = video_pb.LikeVideoResponse
	PublishVideoRequest     = video_pb.PublishVideoRequest
	PublishVideoResponse    = video_pb.PublishVideoResponse
	SearchVideoRequest      = video_pb.SearchVideoRequest
	SearchVideoResponse     = video_pb.SearchVideoResponse
	VideoInfo               = video_pb.VideoInfo
	VideoPopularInfo        = video_pb.VideoPopularInfo

	VideoService interface {
		PublishVideo(ctx context.Context, in *PublishVideoRequest, opts ...grpc.CallOption) (*PublishVideoResponse, error)
		GetFeedVideo(ctx context.Context, in *GetFeedVideoRequest, opts ...grpc.CallOption) (*GetFeedVideoResponse, error)
		GetVideoList(ctx context.Context, in *GetVideoListRequest, opts ...grpc.CallOption) (*GetVideoListResponse, error)
		SearchVideo(ctx context.Context, in *SearchVideoRequest, opts ...grpc.CallOption) (*SearchVideoResponse, error)
		GetPopularVideo(ctx context.Context, in *GetPopularVideoRequest, opts ...grpc.CallOption) (*GetPopularVideoResponse, error)
		LikeVideo(ctx context.Context, in *LikeVideoRequest, opts ...grpc.CallOption) (*LikeVideoResponse, error)
		GetLikeList(ctx context.Context, in *GetLikeListRequest, opts ...grpc.CallOption) (*GetLikeListResponse, error)
	}

	defaultVideoService struct {
		cli zrpc.Client
	}
)

func NewVideoService(cli zrpc.Client) VideoService {
	return &defaultVideoService{
		cli: cli,
	}
}

func (m *defaultVideoService) PublishVideo(ctx context.Context, in *PublishVideoRequest, opts ...grpc.CallOption) (*PublishVideoResponse, error) {
	client := video_pb.NewVideoServiceClient(m.cli.Conn())
	return client.PublishVideo(ctx, in, opts...)
}

func (m *defaultVideoService) GetFeedVideo(ctx context.Context, in *GetFeedVideoRequest, opts ...grpc.CallOption) (*GetFeedVideoResponse, error) {
	client := video_pb.NewVideoServiceClient(m.cli.Conn())
	return client.GetFeedVideo(ctx, in, opts...)
}

func (m *defaultVideoService) GetVideoList(ctx context.Context, in *GetVideoListRequest, opts ...grpc.CallOption) (*GetVideoListResponse, error) {
	client := video_pb.NewVideoServiceClient(m.cli.Conn())
	return client.GetVideoList(ctx, in, opts...)
}

func (m *defaultVideoService) SearchVideo(ctx context.Context, in *SearchVideoRequest, opts ...grpc.CallOption) (*SearchVideoResponse, error) {
	client := video_pb.NewVideoServiceClient(m.cli.Conn())
	return client.SearchVideo(ctx, in, opts...)
}

func (m *defaultVideoService) GetPopularVideo(ctx context.Context, in *GetPopularVideoRequest, opts ...grpc.CallOption) (*GetPopularVideoResponse, error) {
	client := video_pb.NewVideoServiceClient(m.cli.Conn())
	return client.GetPopularVideo(ctx, in, opts...)
}

func (m *defaultVideoService) LikeVideo(ctx context.Context, in *LikeVideoRequest, opts ...grpc.CallOption) (*LikeVideoResponse, error) {
	client := video_pb.NewVideoServiceClient(m.cli.Conn())
	return client.LikeVideo(ctx, in, opts...)
}

func (m *defaultVideoService) GetLikeList(ctx context.Context, in *GetLikeListRequest, opts ...grpc.CallOption) (*GetLikeListResponse, error) {
	client := video_pb.NewVideoServiceClient(m.cli.Conn())
	return client.GetLikeList(ctx, in, opts...)
}
