// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: app/user/rpc/user.proto

package user_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	MfaCode       string                 `protobuf:"bytes,3,opt,name=mfa_code,json=mfaCode,proto3" json:"mfa_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_app_user_rpc_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetMfaCode() string {
	if x != nil {
		return x.MfaCode
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_app_user_rpc_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_app_user_rpc_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_app_user_rpc_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_app_user_rpc_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{4}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_app_user_rpc_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{5}
}

func (x *RefreshTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type GetUserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoRequest) Reset() {
	*x = GetUserInfoRequest{}
	mi := &file_app_user_rpc_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRequest) ProtoMessage() {}

func (x *GetUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserInfoRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	PhotoUrl      string                 `protobuf:"bytes,3,opt,name=photo_url,json=photoUrl,proto3" json:"photo_url,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_app_user_rpc_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{7}
}

func (x *UserInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserInfo) GetPhotoUrl() string {
	if x != nil {
		return x.PhotoUrl
	}
	return ""
}

func (x *UserInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UserInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetUserInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoResponse) Reset() {
	*x = GetUserInfoResponse{}
	mi := &file_app_user_rpc_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResponse) ProtoMessage() {}

func (x *GetUserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResponse.ProtoReflect.Descriptor instead.
func (*GetUserInfoResponse) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserInfoResponse) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserPhotoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Photo         []byte                 `protobuf:"bytes,2,opt,name=photo,proto3" json:"photo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserPhotoRequest) Reset() {
	*x = UpdateUserPhotoRequest{}
	mi := &file_app_user_rpc_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserPhotoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserPhotoRequest) ProtoMessage() {}

func (x *UpdateUserPhotoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserPhotoRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserPhotoRequest) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateUserPhotoRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserPhotoRequest) GetPhoto() []byte {
	if x != nil {
		return x.Photo
	}
	return nil
}

type UpdateUserPhotoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhotoUrl      string                 `protobuf:"bytes,1,opt,name=photo_url,json=photoUrl,proto3" json:"photo_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserPhotoResponse) Reset() {
	*x = UpdateUserPhotoResponse{}
	mi := &file_app_user_rpc_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserPhotoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserPhotoResponse) ProtoMessage() {}

func (x *UpdateUserPhotoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserPhotoResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserPhotoResponse) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateUserPhotoResponse) GetPhotoUrl() string {
	if x != nil {
		return x.PhotoUrl
	}
	return ""
}

type GetMfaQRCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMfaQRCodeRequest) Reset() {
	*x = GetMfaQRCodeRequest{}
	mi := &file_app_user_rpc_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMfaQRCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMfaQRCodeRequest) ProtoMessage() {}

func (x *GetMfaQRCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMfaQRCodeRequest.ProtoReflect.Descriptor instead.
func (*GetMfaQRCodeRequest) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{11}
}

func (x *GetMfaQRCodeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetMfaQRCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MfaSecret     string                 `protobuf:"bytes,1,opt,name=mfa_secret,json=mfaSecret,proto3" json:"mfa_secret,omitempty"`
	QrCodeUrl     string                 `protobuf:"bytes,2,opt,name=qr_code_url,json=qrCodeUrl,proto3" json:"qr_code_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMfaQRCodeResponse) Reset() {
	*x = GetMfaQRCodeResponse{}
	mi := &file_app_user_rpc_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMfaQRCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMfaQRCodeResponse) ProtoMessage() {}

func (x *GetMfaQRCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMfaQRCodeResponse.ProtoReflect.Descriptor instead.
func (*GetMfaQRCodeResponse) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{12}
}

func (x *GetMfaQRCodeResponse) GetMfaSecret() string {
	if x != nil {
		return x.MfaSecret
	}
	return ""
}

func (x *GetMfaQRCodeResponse) GetQrCodeUrl() string {
	if x != nil {
		return x.QrCodeUrl
	}
	return ""
}

type BindMfaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MfaSecret     string                 `protobuf:"bytes,2,opt,name=mfa_secret,json=mfaSecret,proto3" json:"mfa_secret,omitempty"`
	MfaCode       string                 `protobuf:"bytes,3,opt,name=mfa_code,json=mfaCode,proto3" json:"mfa_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindMfaRequest) Reset() {
	*x = BindMfaRequest{}
	mi := &file_app_user_rpc_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindMfaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindMfaRequest) ProtoMessage() {}

func (x *BindMfaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindMfaRequest.ProtoReflect.Descriptor instead.
func (*BindMfaRequest) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{13}
}

func (x *BindMfaRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BindMfaRequest) GetMfaSecret() string {
	if x != nil {
		return x.MfaSecret
	}
	return ""
}

func (x *BindMfaRequest) GetMfaCode() string {
	if x != nil {
		return x.MfaCode
	}
	return ""
}

type BindMfaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindMfaResponse) Reset() {
	*x = BindMfaResponse{}
	mi := &file_app_user_rpc_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindMfaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindMfaResponse) ProtoMessage() {}

func (x *BindMfaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindMfaResponse.ProtoReflect.Descriptor instead.
func (*BindMfaResponse) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{14}
}

type JwchLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JwchLoginRequest) Reset() {
	*x = JwchLoginRequest{}
	mi := &file_app_user_rpc_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JwchLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwchLoginRequest) ProtoMessage() {}

func (x *JwchLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwchLoginRequest.ProtoReflect.Descriptor instead.
func (*JwchLoginRequest) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{15}
}

func (x *JwchLoginRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *JwchLoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *JwchLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type JwchLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JwchLoginResponse) Reset() {
	*x = JwchLoginResponse{}
	mi := &file_app_user_rpc_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JwchLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwchLoginResponse) ProtoMessage() {}

func (x *JwchLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwchLoginResponse.ProtoReflect.Descriptor instead.
func (*JwchLoginResponse) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{16}
}

type JwchGetUserCookieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JwchGetUserCookieRequest) Reset() {
	*x = JwchGetUserCookieRequest{}
	mi := &file_app_user_rpc_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JwchGetUserCookieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwchGetUserCookieRequest) ProtoMessage() {}

func (x *JwchGetUserCookieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwchGetUserCookieRequest.ProtoReflect.Descriptor instead.
func (*JwchGetUserCookieRequest) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{17}
}

func (x *JwchGetUserCookieRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type JwchGetUserCookieResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JwchId        string                 `protobuf:"bytes,1,opt,name=jwch_id,json=jwchId,proto3" json:"jwch_id,omitempty"`
	Cookie        string                 `protobuf:"bytes,2,opt,name=cookie,proto3" json:"cookie,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JwchGetUserCookieResponse) Reset() {
	*x = JwchGetUserCookieResponse{}
	mi := &file_app_user_rpc_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JwchGetUserCookieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwchGetUserCookieResponse) ProtoMessage() {}

func (x *JwchGetUserCookieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwchGetUserCookieResponse.ProtoReflect.Descriptor instead.
func (*JwchGetUserCookieResponse) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{18}
}

func (x *JwchGetUserCookieResponse) GetJwchId() string {
	if x != nil {
		return x.JwchId
	}
	return ""
}

func (x *JwchGetUserCookieResponse) GetCookie() string {
	if x != nil {
		return x.Cookie
	}
	return ""
}

var File_app_user_rpc_user_proto protoreflect.FileDescriptor

const file_app_user_rpc_user_proto_rawDesc = "" +
	"\n" +
	"\x17app/user/rpc/user.proto\x12\x04user\"a\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x19\n" +
	"\bmfa_code\x18\x03 \x01(\tR\amfaCode\"p\n" +
	"\rLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"I\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"+\n" +
	"\x10RegisterResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"^\n" +
	"\x14RefreshTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"-\n" +
	"\x12GetUserInfoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x9a\x01\n" +
	"\bUserInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1b\n" +
	"\tphoto_url\x18\x03 \x01(\tR\bphotoUrl\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\"9\n" +
	"\x13GetUserInfoResponse\x12\"\n" +
	"\x04user\x18\x01 \x01(\v2\x0e.user.UserInfoR\x04user\"G\n" +
	"\x16UpdateUserPhotoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05photo\x18\x02 \x01(\fR\x05photo\"6\n" +
	"\x17UpdateUserPhotoResponse\x12\x1b\n" +
	"\tphoto_url\x18\x01 \x01(\tR\bphotoUrl\".\n" +
	"\x13GetMfaQRCodeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"U\n" +
	"\x14GetMfaQRCodeResponse\x12\x1d\n" +
	"\n" +
	"mfa_secret\x18\x01 \x01(\tR\tmfaSecret\x12\x1e\n" +
	"\vqr_code_url\x18\x02 \x01(\tR\tqrCodeUrl\"c\n" +
	"\x0eBindMfaRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"mfa_secret\x18\x02 \x01(\tR\tmfaSecret\x12\x19\n" +
	"\bmfa_code\x18\x03 \x01(\tR\amfaCode\"\x11\n" +
	"\x0fBindMfaResponse\"c\n" +
	"\x10JwchLoginRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"\x13\n" +
	"\x11JwchLoginResponse\"3\n" +
	"\x18JwchGetUserCookieRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"L\n" +
	"\x19JwchGetUserCookieResponse\x12\x17\n" +
	"\ajwch_id\x18\x01 \x01(\tR\x06jwchId\x12\x16\n" +
	"\x06cookie\x18\x02 \x01(\tR\x06cookie2\xe8\x04\n" +
	"\vUserService\x129\n" +
	"\bRegister\x12\x15.user.RegisterRequest\x1a\x16.user.RegisterResponse\x120\n" +
	"\x05Login\x12\x12.user.LoginRequest\x1a\x13.user.LoginResponse\x12E\n" +
	"\fRefreshToken\x12\x19.user.RefreshTokenRequest\x1a\x1a.user.RefreshTokenResponse\x12B\n" +
	"\vGetUserInfo\x12\x18.user.GetUserInfoRequest\x1a\x19.user.GetUserInfoResponse\x12N\n" +
	"\x0fUpdateUserPhoto\x12\x1c.user.UpdateUserPhotoRequest\x1a\x1d.user.UpdateUserPhotoResponse\x12E\n" +
	"\fGetMfaQRCode\x12\x19.user.GetMfaQRCodeRequest\x1a\x1a.user.GetMfaQRCodeResponse\x126\n" +
	"\aBindMfa\x12\x14.user.BindMfaRequest\x1a\x15.user.BindMfaResponse\x12<\n" +
	"\tJwchLogin\x12\x16.user.JwchLoginRequest\x1a\x17.user.JwchLoginResponse\x12T\n" +
	"\x11JwchGetUserCookie\x12\x1e.user.JwchGetUserCookieRequest\x1a\x1f.user.JwchGetUserCookieResponseB\vZ\t./user_pbb\x06proto3"

var (
	file_app_user_rpc_user_proto_rawDescOnce sync.Once
	file_app_user_rpc_user_proto_rawDescData []byte
)

func file_app_user_rpc_user_proto_rawDescGZIP() []byte {
	file_app_user_rpc_user_proto_rawDescOnce.Do(func() {
		file_app_user_rpc_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_user_rpc_user_proto_rawDesc), len(file_app_user_rpc_user_proto_rawDesc)))
	})
	return file_app_user_rpc_user_proto_rawDescData
}

var file_app_user_rpc_user_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_app_user_rpc_user_proto_goTypes = []any{
	(*LoginRequest)(nil),              // 0: user.LoginRequest
	(*LoginResponse)(nil),             // 1: user.LoginResponse
	(*RegisterRequest)(nil),           // 2: user.RegisterRequest
	(*RegisterResponse)(nil),          // 3: user.RegisterResponse
	(*RefreshTokenRequest)(nil),       // 4: user.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),      // 5: user.RefreshTokenResponse
	(*GetUserInfoRequest)(nil),        // 6: user.GetUserInfoRequest
	(*UserInfo)(nil),                  // 7: user.UserInfo
	(*GetUserInfoResponse)(nil),       // 8: user.GetUserInfoResponse
	(*UpdateUserPhotoRequest)(nil),    // 9: user.UpdateUserPhotoRequest
	(*UpdateUserPhotoResponse)(nil),   // 10: user.UpdateUserPhotoResponse
	(*GetMfaQRCodeRequest)(nil),       // 11: user.GetMfaQRCodeRequest
	(*GetMfaQRCodeResponse)(nil),      // 12: user.GetMfaQRCodeResponse
	(*BindMfaRequest)(nil),            // 13: user.BindMfaRequest
	(*BindMfaResponse)(nil),           // 14: user.BindMfaResponse
	(*JwchLoginRequest)(nil),          // 15: user.JwchLoginRequest
	(*JwchLoginResponse)(nil),         // 16: user.JwchLoginResponse
	(*JwchGetUserCookieRequest)(nil),  // 17: user.JwchGetUserCookieRequest
	(*JwchGetUserCookieResponse)(nil), // 18: user.JwchGetUserCookieResponse
}
var file_app_user_rpc_user_proto_depIdxs = []int32{
	7,  // 0: user.GetUserInfoResponse.user:type_name -> user.UserInfo
	2,  // 1: user.UserService.Register:input_type -> user.RegisterRequest
	0,  // 2: user.UserService.Login:input_type -> user.LoginRequest
	4,  // 3: user.UserService.RefreshToken:input_type -> user.RefreshTokenRequest
	6,  // 4: user.UserService.GetUserInfo:input_type -> user.GetUserInfoRequest
	9,  // 5: user.UserService.UpdateUserPhoto:input_type -> user.UpdateUserPhotoRequest
	11, // 6: user.UserService.GetMfaQRCode:input_type -> user.GetMfaQRCodeRequest
	13, // 7: user.UserService.BindMfa:input_type -> user.BindMfaRequest
	15, // 8: user.UserService.JwchLogin:input_type -> user.JwchLoginRequest
	17, // 9: user.UserService.JwchGetUserCookie:input_type -> user.JwchGetUserCookieRequest
	3,  // 10: user.UserService.Register:output_type -> user.RegisterResponse
	1,  // 11: user.UserService.Login:output_type -> user.LoginResponse
	5,  // 12: user.UserService.RefreshToken:output_type -> user.RefreshTokenResponse
	8,  // 13: user.UserService.GetUserInfo:output_type -> user.GetUserInfoResponse
	10, // 14: user.UserService.UpdateUserPhoto:output_type -> user.UpdateUserPhotoResponse
	12, // 15: user.UserService.GetMfaQRCode:output_type -> user.GetMfaQRCodeResponse
	14, // 16: user.UserService.BindMfa:output_type -> user.BindMfaResponse
	16, // 17: user.UserService.JwchLogin:output_type -> user.JwchLoginResponse
	18, // 18: user.UserService.JwchGetUserCookie:output_type -> user.JwchGetUserCookieResponse
	10, // [10:19] is the sub-list for method output_type
	1,  // [1:10] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_app_user_rpc_user_proto_init() }
func file_app_user_rpc_user_proto_init() {
	if File_app_user_rpc_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_user_rpc_user_proto_rawDesc), len(file_app_user_rpc_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_user_rpc_user_proto_goTypes,
		DependencyIndexes: file_app_user_rpc_user_proto_depIdxs,
		MessageInfos:      file_app_user_rpc_user_proto_msgTypes,
	}.Build()
	File_app_user_rpc_user_proto = out.File
	file_app_user_rpc_user_proto_goTypes = nil
	file_app_user_rpc_user_proto_depIdxs = nil
}
