// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: app/communication/rpc/communication.proto

package communication_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerId    int64                  `protobuf:"varint,1,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ActionType    int32                  `protobuf:"varint,3,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"` // 1-关注 0-取消关注
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_app_communication_rpc_communication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_communication_rpc_communication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_app_communication_rpc_communication_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetFollowerId() int64 {
	if x != nil {
		return x.FollowerId
	}
	return 0
}

func (x *SubscribeRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SubscribeRequest) GetActionType() int32 {
	if x != nil {
		return x.ActionType
	}
	return 0
}

type SubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_app_communication_rpc_communication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_communication_rpc_communication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_app_communication_rpc_communication_proto_rawDescGZIP(), []int{1}
}

type GetFansListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PageNum       int32                  `protobuf:"varint,2,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFansListRequest) Reset() {
	*x = GetFansListRequest{}
	mi := &file_app_communication_rpc_communication_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFansListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFansListRequest) ProtoMessage() {}

func (x *GetFansListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_communication_rpc_communication_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFansListRequest.ProtoReflect.Descriptor instead.
func (*GetFansListRequest) Descriptor() ([]byte, []int) {
	return file_app_communication_rpc_communication_proto_rawDescGZIP(), []int{2}
}

func (x *GetFansListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetFansListRequest) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *GetFansListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetFansListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []int64                `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFansListResponse) Reset() {
	*x = GetFansListResponse{}
	mi := &file_app_communication_rpc_communication_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFansListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFansListResponse) ProtoMessage() {}

func (x *GetFansListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_communication_rpc_communication_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFansListResponse.ProtoReflect.Descriptor instead.
func (*GetFansListResponse) Descriptor() ([]byte, []int) {
	return file_app_communication_rpc_communication_proto_rawDescGZIP(), []int{3}
}

func (x *GetFansListResponse) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *GetFansListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetSubscriberListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PageNum       int32                  `protobuf:"varint,2,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriberListRequest) Reset() {
	*x = GetSubscriberListRequest{}
	mi := &file_app_communication_rpc_communication_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriberListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriberListRequest) ProtoMessage() {}

func (x *GetSubscriberListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_communication_rpc_communication_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriberListRequest.ProtoReflect.Descriptor instead.
func (*GetSubscriberListRequest) Descriptor() ([]byte, []int) {
	return file_app_communication_rpc_communication_proto_rawDescGZIP(), []int{4}
}

func (x *GetSubscriberListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetSubscriberListRequest) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *GetSubscriberListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetSubscriberListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []int64                `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriberListResponse) Reset() {
	*x = GetSubscriberListResponse{}
	mi := &file_app_communication_rpc_communication_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriberListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriberListResponse) ProtoMessage() {}

func (x *GetSubscriberListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_communication_rpc_communication_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriberListResponse.ProtoReflect.Descriptor instead.
func (*GetSubscriberListResponse) Descriptor() ([]byte, []int) {
	return file_app_communication_rpc_communication_proto_rawDescGZIP(), []int{5}
}

func (x *GetSubscriberListResponse) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *GetSubscriberListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetFriendListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PageNum       int32                  `protobuf:"varint,2,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendListRequest) Reset() {
	*x = GetFriendListRequest{}
	mi := &file_app_communication_rpc_communication_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendListRequest) ProtoMessage() {}

func (x *GetFriendListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_communication_rpc_communication_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendListRequest.ProtoReflect.Descriptor instead.
func (*GetFriendListRequest) Descriptor() ([]byte, []int) {
	return file_app_communication_rpc_communication_proto_rawDescGZIP(), []int{6}
}

func (x *GetFriendListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetFriendListRequest) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *GetFriendListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetFriendListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []int64                `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendListResponse) Reset() {
	*x = GetFriendListResponse{}
	mi := &file_app_communication_rpc_communication_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendListResponse) ProtoMessage() {}

func (x *GetFriendListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_communication_rpc_communication_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendListResponse.ProtoReflect.Descriptor instead.
func (*GetFriendListResponse) Descriptor() ([]byte, []int) {
	return file_app_communication_rpc_communication_proto_rawDescGZIP(), []int{7}
}

func (x *GetFriendListResponse) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *GetFriendListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_app_communication_rpc_communication_proto protoreflect.FileDescriptor

const file_app_communication_rpc_communication_proto_rawDesc = "" +
	"\n" +
	")app/communication/rpc/communication.proto\x12\rcommunication\"m\n" +
	"\x10SubscribeRequest\x12\x1f\n" +
	"\vfollower_id\x18\x01 \x01(\x03R\n" +
	"followerId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vaction_type\x18\x03 \x01(\x05R\n" +
	"actionType\"\x13\n" +
	"\x11SubscribeResponse\"e\n" +
	"\x12GetFansListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\bpage_num\x18\x02 \x01(\x05R\apageNum\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"F\n" +
	"\x13GetFansListResponse\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\x03R\auserIds\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"k\n" +
	"\x18GetSubscriberListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\bpage_num\x18\x02 \x01(\x05R\apageNum\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"L\n" +
	"\x19GetSubscriberListResponse\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\x03R\auserIds\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"g\n" +
	"\x14GetFriendListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\bpage_num\x18\x02 \x01(\x05R\apageNum\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"H\n" +
	"\x15GetFriendListResponse\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\x03R\auserIds\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2\x80\x03\n" +
	"\x14CommunicationService\x12N\n" +
	"\tSubscribe\x12\x1f.communication.SubscribeRequest\x1a .communication.SubscribeResponse\x12T\n" +
	"\vGetFansList\x12!.communication.GetFansListRequest\x1a\".communication.GetFansListResponse\x12f\n" +
	"\x11GetSubscriberList\x12'.communication.GetSubscriberListRequest\x1a(.communication.GetSubscriberListResponse\x12Z\n" +
	"\rGetFriendList\x12#.communication.GetFriendListRequest\x1a$.communication.GetFriendListResponseB\x14Z\x12./communication_pbb\x06proto3"

var (
	file_app_communication_rpc_communication_proto_rawDescOnce sync.Once
	file_app_communication_rpc_communication_proto_rawDescData []byte
)

func file_app_communication_rpc_communication_proto_rawDescGZIP() []byte {
	file_app_communication_rpc_communication_proto_rawDescOnce.Do(func() {
		file_app_communication_rpc_communication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_communication_rpc_communication_proto_rawDesc), len(file_app_communication_rpc_communication_proto_rawDesc)))
	})
	return file_app_communication_rpc_communication_proto_rawDescData
}

var file_app_communication_rpc_communication_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_app_communication_rpc_communication_proto_goTypes = []any{
	(*SubscribeRequest)(nil),          // 0: communication.SubscribeRequest
	(*SubscribeResponse)(nil),         // 1: communication.SubscribeResponse
	(*GetFansListRequest)(nil),        // 2: communication.GetFansListRequest
	(*GetFansListResponse)(nil),       // 3: communication.GetFansListResponse
	(*GetSubscriberListRequest)(nil),  // 4: communication.GetSubscriberListRequest
	(*GetSubscriberListResponse)(nil), // 5: communication.GetSubscriberListResponse
	(*GetFriendListRequest)(nil),      // 6: communication.GetFriendListRequest
	(*GetFriendListResponse)(nil),     // 7: communication.GetFriendListResponse
}
var file_app_communication_rpc_communication_proto_depIdxs = []int32{
	0, // 0: communication.CommunicationService.Subscribe:input_type -> communication.SubscribeRequest
	2, // 1: communication.CommunicationService.GetFansList:input_type -> communication.GetFansListRequest
	4, // 2: communication.CommunicationService.GetSubscriberList:input_type -> communication.GetSubscriberListRequest
	6, // 3: communication.CommunicationService.GetFriendList:input_type -> communication.GetFriendListRequest
	1, // 4: communication.CommunicationService.Subscribe:output_type -> communication.SubscribeResponse
	3, // 5: communication.CommunicationService.GetFansList:output_type -> communication.GetFansListResponse
	5, // 6: communication.CommunicationService.GetSubscriberList:output_type -> communication.GetSubscriberListResponse
	7, // 7: communication.CommunicationService.GetFriendList:output_type -> communication.GetFriendListResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_communication_rpc_communication_proto_init() }
func file_app_communication_rpc_communication_proto_init() {
	if File_app_communication_rpc_communication_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_communication_rpc_communication_proto_rawDesc), len(file_app_communication_rpc_communication_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_communication_rpc_communication_proto_goTypes,
		DependencyIndexes: file_app_communication_rpc_communication_proto_depIdxs,
		MessageInfos:      file_app_communication_rpc_communication_proto_msgTypes,
	}.Build()
	File_app_communication_rpc_communication_proto = out.File
	file_app_communication_rpc_communication_proto_goTypes = nil
	file_app_communication_rpc_communication_proto_depIdxs = nil
}
