// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type BaseResponse struct {
	StatusCode int32  `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
}

type BindMfaqrcodeRequest struct {
	Mfa_secret string `form:"mfa_secret"`
	Mfa_code   string `form:"mfa_code"`
}

type BindMfaqrcodeResponse struct {
	Base BaseResponse `json:"base"`
}

type CommentBaseinfo struct {
	CommentID       string `json:"comment_id"`
	UserID          string `json:"user_id"`
	VideoID         string `json:"video_id"`
	Content         string `json:"content"`
	CreatedAt       string `json:"created_at"`
	UpdatedAt       string `json:"updated_at"`
	DeletedAt       string `json:"deleted_at"`
	LikeCount       int32  `json:"like_count"`
	ParentCommentID string `json:"parent_comment_id"`
}

type CommentPareantCommentRequest struct {
	ParentCommentID string `form:"parent_comment_id"`
	CommentText     string `form:"comment_text"`
}

type CommentPareantCommentResponse struct {
	Base      BaseResponse `json:"base_response"`
	CommentID string       `json:"comment_id"`
}

type CommentVideoRequest struct {
	VideoID     string `form:"video_id"`
	CommentText string `form:"comment_text"`
}

type CommentVideoResponse struct {
	Base      BaseResponse `json:"base_response"`
	CommentID string       `json:"comment_id"`
}

type DeleteCommentRequest struct {
	CommentID string `form:"comment_id"`
}

type DeleteCommentResponse struct {
	Base BaseResponse `json:"base_response"`
}

type FeedVideoRequest struct {
	LastTime string `form:"last_time"`
	PageSize int32  `form:"page_size"`
	PageNum  int32  `form:"page_num"`
}

type FeedVideoResponse struct {
	Base   BaseResponse `json:"base"`
	Total  int64        `json:"total"`
	Videos []Item       `json:"items"`
}

type GetCommentListRequest struct {
	VideoID    string `form:"video_id"`
	PageNumber int32  `form:"page_number"`
	PageSize   int32  `form:"page_size"`
}

type GetCommentListResponse struct {
	Base         BaseResponse      `json:"base_response"`
	CommentList  []CommentBaseinfo `json:"comment_list"`
	CommentCount int32             `json:"comment_count"`
}

type GetFansListRequest struct {
	PageNumber int32 `form:"page_number"`
	PageSize   int32 `form:"page_size"`
}

type GetFansListResponse struct {
	BaseResponse BaseResponse   `json:"base_response"`
	FansList     []UserBaseinfo `json:"fans_list"`
	FansCount    int32          `json:"fans_count"`
}

type GetFriendListRequest struct {
	PageNumber int32 `form:"page_number"`
	PageSize   int32 `form:"page_size"`
}

type GetFriendListResponse struct {
	BaseResponse BaseResponse   `json:"base_response"`
	FriendList   []UserBaseinfo `json:"friend_list"`
	FriendCount  int32          `json:"friend_count"`
}

type GetLikeListRequest struct {
	PageNumber int32 `form:"page_number"`
	PageSize   int32 `form:"page_size"`
}

type GetLikeListResponse struct {
	Base      BaseResponse    `json:"base_response"`
	VideoList []VideoBaseinfo `json:"video_list"`
	LikeCount int32           `json:"like_count"`
}

type GetSubscriberListRequest struct {
	PageNumber int32 `form:"page_number"`
	PageSize   int32 `form:"page_size"`
}

type GetSubscriberListResponse struct {
	BaseResponse    BaseResponse   `json:"base_response"`
	SubscriberList  []UserBaseinfo `json:"subscriber_list"`
	SubscriberCount int32          `json:"subscriber_count"`
}

type GetVideoListRequest struct {
	UserID   string `form:"user_id"`
	PageSize int32  `form:"page_size"`
	PageNum  int32  `form:"page_num"`
}

type GetVideoListResponse struct {
	Base   BaseResponse    `json:"base"`
	Videos []VideoBaseinfo `json:"videos"`
}

type Item struct {
	Videos        VideoBaseinfo `json:"videos"`
	VideosPopular VideoPopular  `json:"videos_popular"`
}

type JwchGetUserCookieRequest struct {
}

type JwchGetUserCookieResponse struct {
	Base   BaseResponse `json:"base"`
	JwchID string       `json:"jwch_id"`
	Cookie string       `json:"cookie" `
}

type JwchLoginRequest struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type JwchLoginResponse struct {
	Base BaseResponse `json:"base"`
}

type LikeCommentRequest struct {
	CommentID string `form:"comment_id"`
	Liketype  int32  `form:"like_type"`
}

type LikeCommentResponse struct {
	Base BaseResponse `json:"base_response"`
}

type LikeVideoRequest struct {
	VideoID    string `form:"video_id"`
	ActionType int32  `form:"action_type"`
}

type LikeVideoResponse struct {
	Base BaseResponse `json:"base_response"`
}

type LoginRequest struct {
	Username string `form:"username"`
	Password string `form:"password"`
	MfaCode  string `form:"mfa_code"`
}

type LoginResponse struct {
	Base         BaseResponse `json:"base"`
	UserID       string       `json:"user_id"`
	AccessToken  string       `json:"access_token"`
	RefreshToken string       `json:"refresh_token" cookie:"refresh_token"`
}

type MfaqrcodeRequest struct {
	Mfa_ticket string `form:"mfa_ticket"`
}

type MfaqrcodeResponse struct {
	Base       BaseResponse `json:"base"`
	QRCodeURL  string       `json:"qr_code"`
	Mfa_secret string       `json:"mfa_secret"`
}

type PublishVideoRequest struct {
	Title       string `form:"title"`
	Description string `form:"description"`
}

type PublishVideoResponse struct {
	Base    BaseResponse `json:"base"`
	VideoID string       `json:"video_id"`
}

type RefreshTokenRequest struct {
	RefreshToken string `cookie:"refresh_token"`
}

type RefreshTokenResponse struct {
	Base         BaseResponse `json:"base"`
	AccessToken  string       `json:"access_token"`
	RefreshToken string       `json:"refresh_token" cookie:"refresh_token"`
}

type RegisterRequest struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type RegisterResponse struct {
	Base   BaseResponse `json:"base"`
	UserID string       `json:"user_id"`
}

type SubscribeRequest struct {
	ToUserID   string `form:"to_user_id"`
	ActionType int32  `form:"action_type"`
}

type SubscribeResponse struct {
	BaseResponse BaseResponse `json:"base_response"`
}

type UserBaseinfo struct {
	UserID    string `json:"user_id"`
	Username  string `json:"username"`
	Password  string `json:"password"`
	PhotoURL  string `json:"photo_url"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
	DeletedAt string `json:"deleted_at"`
}

type UserFollow struct {
	FollowerID string `json:"follower_id"`
	UserID     string `json:"user_id"`
	Status     int32  `json:"status"`
}

type UserInfoRequest struct {
	UserID string `form:"user_id"`
}

type UserInfoResponse struct {
	Base BaseResponse `json:"base"`
	User UserBaseinfo `json:"user"`
}

type UserphotoRequest struct {
	PhotoURL string `form:"photo_url"`
}

type UserphotoResponse struct {
	StatusCode int32  `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
}

type VideoBaseinfo struct {
	VideoID     string `json:"video_id"`
	AuthorID    string `json:"author_id"`
	VideoURL    string `json:"video_url"`
	CoverURL    string `json:"cover_url"`
	Title       string `json:"title"`
	Description string `json:"description"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
	DeletedAt   string `json:"deleted_at"`
}

type VideoPopular struct {
	VideoID      string `json:"video_id"`
	VisitCount   int64  `json:"visit_count"`
	LikeCount    int64  `json:"like_count"`
	CommentCount int64  `json:"comment_count"`
}

type VideoPopularRequest struct {
	PageSize int32 `form:"page_size"`
	PageNum  int32 `form:"page_num"`
}

type VideoPopularResponse struct {
	Base   BaseResponse `json:"base"`
	Videos []Item       `json:"items"`
}

type VideoSearchRequest struct {
	Keyword  string `form:"keyword"`
	PageSize int32  `form:"page_size"`
	PageNum  int32  `form:"page_num"`
}

type VideoSearchResponse struct {
	Base   BaseResponse    `json:"base"`
	Videos []VideoBaseinfo `json:"videos"`
}
